/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_power_capping_extra.h"

static const char* CMockString_get_average_power = "get_average_power";
static const char* CMockString_get_averaging_interval = "get_averaging_interval";
static const char* CMockString_get_averaging_interval_range = "get_averaging_interval_range";
static const char* CMockString_get_averaging_interval_step = "get_averaging_interval_step";
static const char* CMockString_get_power_limit = "get_power_limit";
static const char* CMockString_id = "id";
static const char* CMockString_input = "input";
static const char* CMockString_max_pai = "max_pai";
static const char* CMockString_min_pai = "min_pai";
static const char* CMockString_output = "output";
static const char* CMockString_pai = "pai";
static const char* CMockString_pai_step = "pai_step";
static const char* CMockString_power = "power";
static const char* CMockString_power_limit = "power_limit";
static const char* CMockString_set_averaging_interval = "set_averaging_interval";
static const char* CMockString_set_point = "set_point";
static const char* CMockString_update = "update";

typedef struct _CMOCK_get_power_limit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  uint32_t* Expected_power_limit;
  int Expected_power_limit_Depth;
  char ReturnThruPtr_power_limit_Used;
  uint32_t* ReturnThruPtr_power_limit_Val;
  size_t ReturnThruPtr_power_limit_Size;
  char IgnoreArg_id;
  char IgnoreArg_power_limit;

} CMOCK_get_power_limit_CALL_INSTANCE;

typedef struct _CMOCK_get_average_power_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  uint32_t* Expected_power;
  int Expected_power_Depth;
  char ReturnThruPtr_power_Used;
  uint32_t* ReturnThruPtr_power_Val;
  size_t ReturnThruPtr_power_Size;
  char IgnoreArg_id;
  char IgnoreArg_power;

} CMOCK_get_average_power_CALL_INSTANCE;

typedef struct _CMOCK_set_averaging_interval_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  uint32_t Expected_pai;
  char IgnoreArg_id;
  char IgnoreArg_pai;

} CMOCK_set_averaging_interval_CALL_INSTANCE;

typedef struct _CMOCK_get_averaging_interval_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  uint32_t* Expected_pai;
  int Expected_pai_Depth;
  char ReturnThruPtr_pai_Used;
  uint32_t* ReturnThruPtr_pai_Val;
  size_t ReturnThruPtr_pai_Size;
  char IgnoreArg_id;
  char IgnoreArg_pai;

} CMOCK_get_averaging_interval_CALL_INSTANCE;

typedef struct _CMOCK_get_averaging_interval_step_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  uint32_t* Expected_pai_step;
  int Expected_pai_step_Depth;
  char ReturnThruPtr_pai_step_Used;
  uint32_t* ReturnThruPtr_pai_step_Val;
  size_t ReturnThruPtr_pai_step_Size;
  char IgnoreArg_id;
  char IgnoreArg_pai_step;

} CMOCK_get_averaging_interval_step_CALL_INSTANCE;

typedef struct _CMOCK_get_averaging_interval_range_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  uint32_t* Expected_min_pai;
  uint32_t* Expected_max_pai;
  int Expected_min_pai_Depth;
  int Expected_max_pai_Depth;
  char ReturnThruPtr_min_pai_Used;
  uint32_t* ReturnThruPtr_min_pai_Val;
  size_t ReturnThruPtr_min_pai_Size;
  char ReturnThruPtr_max_pai_Used;
  uint32_t* ReturnThruPtr_max_pai_Val;
  size_t ReturnThruPtr_max_pai_Size;
  char IgnoreArg_id;
  char IgnoreArg_min_pai;
  char IgnoreArg_max_pai;

} CMOCK_get_averaging_interval_range_CALL_INSTANCE;

typedef struct _CMOCK_update_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  int64_t Expected_input;
  int64_t* Expected_output;
  int Expected_output_Depth;
  char ReturnThruPtr_output_Used;
  int64_t* ReturnThruPtr_output_Val;
  size_t ReturnThruPtr_output_Size;
  char IgnoreArg_id;
  char IgnoreArg_input;
  char IgnoreArg_output;

} CMOCK_update_CALL_INSTANCE;

typedef struct _CMOCK_set_point_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  int64_t Expected_input;
  char IgnoreArg_id;
  char IgnoreArg_input;

} CMOCK_set_point_CALL_INSTANCE;

static struct Mockmod_power_capping_extraInstance
{
  char get_power_limit_IgnoreBool;
  int get_power_limit_FinalReturn;
  char get_power_limit_CallbackBool;
  CMOCK_get_power_limit_CALLBACK get_power_limit_CallbackFunctionPointer;
  int get_power_limit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_power_limit_CallInstance;
  char get_average_power_IgnoreBool;
  int get_average_power_FinalReturn;
  char get_average_power_CallbackBool;
  CMOCK_get_average_power_CALLBACK get_average_power_CallbackFunctionPointer;
  int get_average_power_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_average_power_CallInstance;
  char set_averaging_interval_IgnoreBool;
  int set_averaging_interval_FinalReturn;
  char set_averaging_interval_CallbackBool;
  CMOCK_set_averaging_interval_CALLBACK set_averaging_interval_CallbackFunctionPointer;
  int set_averaging_interval_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE set_averaging_interval_CallInstance;
  char get_averaging_interval_IgnoreBool;
  int get_averaging_interval_FinalReturn;
  char get_averaging_interval_CallbackBool;
  CMOCK_get_averaging_interval_CALLBACK get_averaging_interval_CallbackFunctionPointer;
  int get_averaging_interval_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_averaging_interval_CallInstance;
  char get_averaging_interval_step_IgnoreBool;
  int get_averaging_interval_step_FinalReturn;
  char get_averaging_interval_step_CallbackBool;
  CMOCK_get_averaging_interval_step_CALLBACK get_averaging_interval_step_CallbackFunctionPointer;
  int get_averaging_interval_step_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_averaging_interval_step_CallInstance;
  char get_averaging_interval_range_IgnoreBool;
  int get_averaging_interval_range_FinalReturn;
  char get_averaging_interval_range_CallbackBool;
  CMOCK_get_averaging_interval_range_CALLBACK get_averaging_interval_range_CallbackFunctionPointer;
  int get_averaging_interval_range_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_averaging_interval_range_CallInstance;
  char update_IgnoreBool;
  int update_FinalReturn;
  char update_CallbackBool;
  CMOCK_update_CALLBACK update_CallbackFunctionPointer;
  int update_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE update_CallInstance;
  char set_point_IgnoreBool;
  int set_point_FinalReturn;
  char set_point_CallbackBool;
  CMOCK_set_point_CALLBACK set_point_CallbackFunctionPointer;
  int set_point_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE set_point_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_power_capping_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.get_power_limit_CallInstance;
  if (Mock.get_power_limit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_power_limit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_power_limit_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.get_average_power_CallInstance;
  if (Mock.get_average_power_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_average_power);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_average_power_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.set_averaging_interval_CallInstance;
  if (Mock.set_averaging_interval_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_set_averaging_interval);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.set_averaging_interval_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.get_averaging_interval_CallInstance;
  if (Mock.get_averaging_interval_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_averaging_interval);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_averaging_interval_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.get_averaging_interval_step_CallInstance;
  if (Mock.get_averaging_interval_step_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_averaging_interval_step);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_averaging_interval_step_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.get_averaging_interval_range_CallInstance;
  if (Mock.get_averaging_interval_range_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_averaging_interval_range);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_averaging_interval_range_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.get_average_power_CallInstance;
  if (Mock.get_average_power_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_average_power);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_average_power_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.set_averaging_interval_CallInstance;
  if (Mock.set_averaging_interval_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_set_averaging_interval);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.set_averaging_interval_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.get_averaging_interval_CallInstance;
  if (Mock.get_averaging_interval_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_averaging_interval);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_averaging_interval_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.get_averaging_interval_step_CallInstance;
  if (Mock.get_averaging_interval_step_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_averaging_interval_step);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_averaging_interval_step_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.get_averaging_interval_range_CallInstance;
  if (Mock.get_averaging_interval_range_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_averaging_interval_range);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_averaging_interval_range_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.update_CallInstance;
  if (Mock.update_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_update);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.update_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.set_point_CallInstance;
  if (Mock.set_point_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_set_point);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.set_point_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_power_capping_extra_Init(void)
{
  Mockmod_power_capping_extra_Destroy();
}

void Mockmod_power_capping_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int get_power_limit(fwk_id_t id, uint32_t* power_limit)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_power_limit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_power_limit);
  cmock_call_instance = (CMOCK_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_power_limit_CallInstance);
  Mock.get_power_limit_CallInstance = CMock_Guts_MemNext(Mock.get_power_limit_CallInstance);
  if (Mock.get_power_limit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_power_limit_FinalReturn;
    Mock.get_power_limit_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_power_limit_CallbackBool &&
      Mock.get_power_limit_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.get_power_limit_CallbackFunctionPointer(id, power_limit, Mock.get_power_limit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_get_power_limit,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_power_limit)
  {
    UNITY_SET_DETAILS(CMockString_get_power_limit,CMockString_power_limit);
    if (cmock_call_instance->Expected_power_limit == NULL)
      { UNITY_TEST_ASSERT_NULL(power_limit, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_power_limit, power_limit, cmock_call_instance->Expected_power_limit_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.get_power_limit_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_power_limit_CallbackFunctionPointer(id, power_limit, Mock.get_power_limit_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_power_limit_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(power_limit, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)power_limit, (void*)cmock_call_instance->ReturnThruPtr_power_limit_Val,
      cmock_call_instance->ReturnThruPtr_power_limit_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_power_limit(CMOCK_get_power_limit_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* power_limit, int power_limit_Depth);
void CMockExpectParameters_get_power_limit(CMOCK_get_power_limit_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* power_limit, int power_limit_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  cmock_call_instance->Expected_power_limit = power_limit;
  cmock_call_instance->Expected_power_limit_Depth = power_limit_Depth;
  cmock_call_instance->IgnoreArg_power_limit = 0;
  cmock_call_instance->ReturnThruPtr_power_limit_Used = 0;
}

void get_power_limit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_power_limit_CALL_INSTANCE));
  CMOCK_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_power_limit_CallInstance = CMock_Guts_MemChain(Mock.get_power_limit_CallInstance, cmock_guts_index);
  Mock.get_power_limit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_power_limit_IgnoreBool = (char)1;
}

void get_power_limit_CMockStopIgnore(void)
{
  if(Mock.get_power_limit_IgnoreBool)
    Mock.get_power_limit_CallInstance = CMock_Guts_MemNext(Mock.get_power_limit_CallInstance);
  Mock.get_power_limit_IgnoreBool = (char)0;
}

void get_power_limit_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_power_limit_CALL_INSTANCE));
  CMOCK_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_power_limit_CallInstance = CMock_Guts_MemChain(Mock.get_power_limit_CallInstance, cmock_guts_index);
  Mock.get_power_limit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_power_limit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* power_limit, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_power_limit_CALL_INSTANCE));
  CMOCK_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_power_limit_CallInstance = CMock_Guts_MemChain(Mock.get_power_limit_CallInstance, cmock_guts_index);
  Mock.get_power_limit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_power_limit(cmock_call_instance, id, power_limit, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_power_limit_AddCallback(CMOCK_get_power_limit_CALLBACK Callback)
{
  Mock.get_power_limit_IgnoreBool = (char)0;
  Mock.get_power_limit_CallbackBool = (char)1;
  Mock.get_power_limit_CallbackFunctionPointer = Callback;
}

void get_power_limit_Stub(CMOCK_get_power_limit_CALLBACK Callback)
{
  Mock.get_power_limit_IgnoreBool = (char)0;
  Mock.get_power_limit_CallbackBool = (char)0;
  Mock.get_power_limit_CallbackFunctionPointer = Callback;
}

void get_power_limit_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* power_limit, int power_limit_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_power_limit_CALL_INSTANCE));
  CMOCK_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_power_limit_CallInstance = CMock_Guts_MemChain(Mock.get_power_limit_CallInstance, cmock_guts_index);
  Mock.get_power_limit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_power_limit(cmock_call_instance, id, power_limit, power_limit_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_power_limit_CMockReturnMemThruPtr_power_limit(UNITY_LINE_TYPE cmock_line, uint32_t* power_limit, size_t cmock_size)
{
  CMOCK_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_power_limit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_power_limit_Used = 1;
  cmock_call_instance->ReturnThruPtr_power_limit_Val = power_limit;
  cmock_call_instance->ReturnThruPtr_power_limit_Size = cmock_size;
}

void get_power_limit_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_power_limit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void get_power_limit_CMockIgnoreArg_power_limit(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_power_limit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_power_limit = 1;
}

int get_average_power(fwk_id_t id, uint32_t* power)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_average_power_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_average_power);
  cmock_call_instance = (CMOCK_get_average_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_average_power_CallInstance);
  Mock.get_average_power_CallInstance = CMock_Guts_MemNext(Mock.get_average_power_CallInstance);
  if (Mock.get_average_power_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_average_power_FinalReturn;
    Mock.get_average_power_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_average_power_CallbackBool &&
      Mock.get_average_power_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.get_average_power_CallbackFunctionPointer(id, power, Mock.get_average_power_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_get_average_power,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_power)
  {
    UNITY_SET_DETAILS(CMockString_get_average_power,CMockString_power);
    if (cmock_call_instance->Expected_power == NULL)
      { UNITY_TEST_ASSERT_NULL(power, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_power, power, cmock_call_instance->Expected_power_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.get_average_power_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_average_power_CallbackFunctionPointer(id, power, Mock.get_average_power_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_power_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(power, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)power, (void*)cmock_call_instance->ReturnThruPtr_power_Val,
      cmock_call_instance->ReturnThruPtr_power_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_average_power(CMOCK_get_average_power_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* power, int power_Depth);
void CMockExpectParameters_get_average_power(CMOCK_get_average_power_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* power, int power_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  cmock_call_instance->Expected_power = power;
  cmock_call_instance->Expected_power_Depth = power_Depth;
  cmock_call_instance->IgnoreArg_power = 0;
  cmock_call_instance->ReturnThruPtr_power_Used = 0;
}

void get_average_power_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_average_power_CALL_INSTANCE));
  CMOCK_get_average_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_average_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_average_power_CallInstance = CMock_Guts_MemChain(Mock.get_average_power_CallInstance, cmock_guts_index);
  Mock.get_average_power_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_average_power_IgnoreBool = (char)1;
}

void get_average_power_CMockStopIgnore(void)
{
  if(Mock.get_average_power_IgnoreBool)
    Mock.get_average_power_CallInstance = CMock_Guts_MemNext(Mock.get_average_power_CallInstance);
  Mock.get_average_power_IgnoreBool = (char)0;
}

void get_average_power_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_average_power_CALL_INSTANCE));
  CMOCK_get_average_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_average_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_average_power_CallInstance = CMock_Guts_MemChain(Mock.get_average_power_CallInstance, cmock_guts_index);
  Mock.get_average_power_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_average_power_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* power, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_average_power_CALL_INSTANCE));
  CMOCK_get_average_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_average_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_average_power_CallInstance = CMock_Guts_MemChain(Mock.get_average_power_CallInstance, cmock_guts_index);
  Mock.get_average_power_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_average_power(cmock_call_instance, id, power, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_average_power_AddCallback(CMOCK_get_average_power_CALLBACK Callback)
{
  Mock.get_average_power_IgnoreBool = (char)0;
  Mock.get_average_power_CallbackBool = (char)1;
  Mock.get_average_power_CallbackFunctionPointer = Callback;
}

void get_average_power_Stub(CMOCK_get_average_power_CALLBACK Callback)
{
  Mock.get_average_power_IgnoreBool = (char)0;
  Mock.get_average_power_CallbackBool = (char)0;
  Mock.get_average_power_CallbackFunctionPointer = Callback;
}

void get_average_power_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* power, int power_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_average_power_CALL_INSTANCE));
  CMOCK_get_average_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_average_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_average_power_CallInstance = CMock_Guts_MemChain(Mock.get_average_power_CallInstance, cmock_guts_index);
  Mock.get_average_power_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_average_power(cmock_call_instance, id, power, power_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_average_power_CMockReturnMemThruPtr_power(UNITY_LINE_TYPE cmock_line, uint32_t* power, size_t cmock_size)
{
  CMOCK_get_average_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_average_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_average_power_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_power_Used = 1;
  cmock_call_instance->ReturnThruPtr_power_Val = power;
  cmock_call_instance->ReturnThruPtr_power_Size = cmock_size;
}

void get_average_power_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_average_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_average_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_average_power_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void get_average_power_CMockIgnoreArg_power(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_average_power_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_average_power_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_average_power_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_power = 1;
}

int set_averaging_interval(fwk_id_t id, uint32_t pai)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_set_averaging_interval_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_set_averaging_interval);
  cmock_call_instance = (CMOCK_set_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.set_averaging_interval_CallInstance);
  Mock.set_averaging_interval_CallInstance = CMock_Guts_MemNext(Mock.set_averaging_interval_CallInstance);
  if (Mock.set_averaging_interval_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.set_averaging_interval_FinalReturn;
    Mock.set_averaging_interval_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.set_averaging_interval_CallbackBool &&
      Mock.set_averaging_interval_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.set_averaging_interval_CallbackFunctionPointer(id, pai, Mock.set_averaging_interval_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_set_averaging_interval,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_pai)
  {
    UNITY_SET_DETAILS(CMockString_set_averaging_interval,CMockString_pai);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_pai, pai, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.set_averaging_interval_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.set_averaging_interval_CallbackFunctionPointer(id, pai, Mock.set_averaging_interval_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_set_averaging_interval(CMOCK_set_averaging_interval_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t pai);
void CMockExpectParameters_set_averaging_interval(CMOCK_set_averaging_interval_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t pai)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  cmock_call_instance->Expected_pai = pai;
  cmock_call_instance->IgnoreArg_pai = 0;
}

void set_averaging_interval_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_averaging_interval_CALL_INSTANCE));
  CMOCK_set_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_averaging_interval_CallInstance = CMock_Guts_MemChain(Mock.set_averaging_interval_CallInstance, cmock_guts_index);
  Mock.set_averaging_interval_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.set_averaging_interval_IgnoreBool = (char)1;
}

void set_averaging_interval_CMockStopIgnore(void)
{
  if(Mock.set_averaging_interval_IgnoreBool)
    Mock.set_averaging_interval_CallInstance = CMock_Guts_MemNext(Mock.set_averaging_interval_CallInstance);
  Mock.set_averaging_interval_IgnoreBool = (char)0;
}

void set_averaging_interval_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_averaging_interval_CALL_INSTANCE));
  CMOCK_set_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_averaging_interval_CallInstance = CMock_Guts_MemChain(Mock.set_averaging_interval_CallInstance, cmock_guts_index);
  Mock.set_averaging_interval_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void set_averaging_interval_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t pai, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_averaging_interval_CALL_INSTANCE));
  CMOCK_set_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_averaging_interval_CallInstance = CMock_Guts_MemChain(Mock.set_averaging_interval_CallInstance, cmock_guts_index);
  Mock.set_averaging_interval_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_set_averaging_interval(cmock_call_instance, id, pai);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void set_averaging_interval_AddCallback(CMOCK_set_averaging_interval_CALLBACK Callback)
{
  Mock.set_averaging_interval_IgnoreBool = (char)0;
  Mock.set_averaging_interval_CallbackBool = (char)1;
  Mock.set_averaging_interval_CallbackFunctionPointer = Callback;
}

void set_averaging_interval_Stub(CMOCK_set_averaging_interval_CALLBACK Callback)
{
  Mock.set_averaging_interval_IgnoreBool = (char)0;
  Mock.set_averaging_interval_CallbackBool = (char)0;
  Mock.set_averaging_interval_CallbackFunctionPointer = Callback;
}

void set_averaging_interval_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_set_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.set_averaging_interval_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void set_averaging_interval_CMockIgnoreArg_pai(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_set_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.set_averaging_interval_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pai = 1;
}

int get_averaging_interval(fwk_id_t id, uint32_t* pai)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_averaging_interval_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_averaging_interval);
  cmock_call_instance = (CMOCK_get_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_averaging_interval_CallInstance);
  Mock.get_averaging_interval_CallInstance = CMock_Guts_MemNext(Mock.get_averaging_interval_CallInstance);
  if (Mock.get_averaging_interval_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_averaging_interval_FinalReturn;
    Mock.get_averaging_interval_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_averaging_interval_CallbackBool &&
      Mock.get_averaging_interval_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.get_averaging_interval_CallbackFunctionPointer(id, pai, Mock.get_averaging_interval_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_get_averaging_interval,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_pai)
  {
    UNITY_SET_DETAILS(CMockString_get_averaging_interval,CMockString_pai);
    if (cmock_call_instance->Expected_pai == NULL)
      { UNITY_TEST_ASSERT_NULL(pai, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_pai, pai, cmock_call_instance->Expected_pai_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.get_averaging_interval_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_averaging_interval_CallbackFunctionPointer(id, pai, Mock.get_averaging_interval_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_pai_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(pai, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)pai, (void*)cmock_call_instance->ReturnThruPtr_pai_Val,
      cmock_call_instance->ReturnThruPtr_pai_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_averaging_interval(CMOCK_get_averaging_interval_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* pai, int pai_Depth);
void CMockExpectParameters_get_averaging_interval(CMOCK_get_averaging_interval_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* pai, int pai_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  cmock_call_instance->Expected_pai = pai;
  cmock_call_instance->Expected_pai_Depth = pai_Depth;
  cmock_call_instance->IgnoreArg_pai = 0;
  cmock_call_instance->ReturnThruPtr_pai_Used = 0;
}

void get_averaging_interval_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_CALL_INSTANCE));
  CMOCK_get_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_averaging_interval_IgnoreBool = (char)1;
}

void get_averaging_interval_CMockStopIgnore(void)
{
  if(Mock.get_averaging_interval_IgnoreBool)
    Mock.get_averaging_interval_CallInstance = CMock_Guts_MemNext(Mock.get_averaging_interval_CallInstance);
  Mock.get_averaging_interval_IgnoreBool = (char)0;
}

void get_averaging_interval_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_CALL_INSTANCE));
  CMOCK_get_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_averaging_interval_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* pai, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_CALL_INSTANCE));
  CMOCK_get_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_averaging_interval(cmock_call_instance, id, pai, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_averaging_interval_AddCallback(CMOCK_get_averaging_interval_CALLBACK Callback)
{
  Mock.get_averaging_interval_IgnoreBool = (char)0;
  Mock.get_averaging_interval_CallbackBool = (char)1;
  Mock.get_averaging_interval_CallbackFunctionPointer = Callback;
}

void get_averaging_interval_Stub(CMOCK_get_averaging_interval_CALLBACK Callback)
{
  Mock.get_averaging_interval_IgnoreBool = (char)0;
  Mock.get_averaging_interval_CallbackBool = (char)0;
  Mock.get_averaging_interval_CallbackFunctionPointer = Callback;
}

void get_averaging_interval_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* pai, int pai_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_CALL_INSTANCE));
  CMOCK_get_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_averaging_interval(cmock_call_instance, id, pai, pai_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_averaging_interval_CMockReturnMemThruPtr_pai(UNITY_LINE_TYPE cmock_line, uint32_t* pai, size_t cmock_size)
{
  CMOCK_get_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_averaging_interval_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pai_Used = 1;
  cmock_call_instance->ReturnThruPtr_pai_Val = pai;
  cmock_call_instance->ReturnThruPtr_pai_Size = cmock_size;
}

void get_averaging_interval_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_averaging_interval_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void get_averaging_interval_CMockIgnoreArg_pai(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_averaging_interval_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_averaging_interval_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pai = 1;
}

int get_averaging_interval_step(fwk_id_t id, uint32_t* pai_step)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_averaging_interval_step_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_averaging_interval_step);
  cmock_call_instance = (CMOCK_get_averaging_interval_step_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_averaging_interval_step_CallInstance);
  Mock.get_averaging_interval_step_CallInstance = CMock_Guts_MemNext(Mock.get_averaging_interval_step_CallInstance);
  if (Mock.get_averaging_interval_step_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_averaging_interval_step_FinalReturn;
    Mock.get_averaging_interval_step_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_averaging_interval_step_CallbackBool &&
      Mock.get_averaging_interval_step_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.get_averaging_interval_step_CallbackFunctionPointer(id, pai_step, Mock.get_averaging_interval_step_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_get_averaging_interval_step,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_pai_step)
  {
    UNITY_SET_DETAILS(CMockString_get_averaging_interval_step,CMockString_pai_step);
    if (cmock_call_instance->Expected_pai_step == NULL)
      { UNITY_TEST_ASSERT_NULL(pai_step, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_pai_step, pai_step, cmock_call_instance->Expected_pai_step_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.get_averaging_interval_step_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_averaging_interval_step_CallbackFunctionPointer(id, pai_step, Mock.get_averaging_interval_step_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_pai_step_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(pai_step, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)pai_step, (void*)cmock_call_instance->ReturnThruPtr_pai_step_Val,
      cmock_call_instance->ReturnThruPtr_pai_step_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_averaging_interval_step(CMOCK_get_averaging_interval_step_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* pai_step, int pai_step_Depth);
void CMockExpectParameters_get_averaging_interval_step(CMOCK_get_averaging_interval_step_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* pai_step, int pai_step_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  cmock_call_instance->Expected_pai_step = pai_step;
  cmock_call_instance->Expected_pai_step_Depth = pai_step_Depth;
  cmock_call_instance->IgnoreArg_pai_step = 0;
  cmock_call_instance->ReturnThruPtr_pai_step_Used = 0;
}

void get_averaging_interval_step_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_step_CALL_INSTANCE));
  CMOCK_get_averaging_interval_step_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_step_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_step_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_step_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_step_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_averaging_interval_step_IgnoreBool = (char)1;
}

void get_averaging_interval_step_CMockStopIgnore(void)
{
  if(Mock.get_averaging_interval_step_IgnoreBool)
    Mock.get_averaging_interval_step_CallInstance = CMock_Guts_MemNext(Mock.get_averaging_interval_step_CallInstance);
  Mock.get_averaging_interval_step_IgnoreBool = (char)0;
}

void get_averaging_interval_step_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_step_CALL_INSTANCE));
  CMOCK_get_averaging_interval_step_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_step_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_step_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_step_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_step_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_averaging_interval_step_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* pai_step, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_step_CALL_INSTANCE));
  CMOCK_get_averaging_interval_step_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_step_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_step_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_step_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_step_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_averaging_interval_step(cmock_call_instance, id, pai_step, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_averaging_interval_step_AddCallback(CMOCK_get_averaging_interval_step_CALLBACK Callback)
{
  Mock.get_averaging_interval_step_IgnoreBool = (char)0;
  Mock.get_averaging_interval_step_CallbackBool = (char)1;
  Mock.get_averaging_interval_step_CallbackFunctionPointer = Callback;
}

void get_averaging_interval_step_Stub(CMOCK_get_averaging_interval_step_CALLBACK Callback)
{
  Mock.get_averaging_interval_step_IgnoreBool = (char)0;
  Mock.get_averaging_interval_step_CallbackBool = (char)0;
  Mock.get_averaging_interval_step_CallbackFunctionPointer = Callback;
}

void get_averaging_interval_step_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* pai_step, int pai_step_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_step_CALL_INSTANCE));
  CMOCK_get_averaging_interval_step_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_step_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_step_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_step_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_step_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_averaging_interval_step(cmock_call_instance, id, pai_step, pai_step_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_averaging_interval_step_CMockReturnMemThruPtr_pai_step(UNITY_LINE_TYPE cmock_line, uint32_t* pai_step, size_t cmock_size)
{
  CMOCK_get_averaging_interval_step_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_step_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_averaging_interval_step_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pai_step_Used = 1;
  cmock_call_instance->ReturnThruPtr_pai_step_Val = pai_step;
  cmock_call_instance->ReturnThruPtr_pai_step_Size = cmock_size;
}

void get_averaging_interval_step_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_averaging_interval_step_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_step_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_averaging_interval_step_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void get_averaging_interval_step_CMockIgnoreArg_pai_step(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_averaging_interval_step_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_step_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_averaging_interval_step_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pai_step = 1;
}

int get_averaging_interval_range(fwk_id_t id, uint32_t* min_pai, uint32_t* max_pai)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_averaging_interval_range);
  cmock_call_instance = (CMOCK_get_averaging_interval_range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_averaging_interval_range_CallInstance);
  Mock.get_averaging_interval_range_CallInstance = CMock_Guts_MemNext(Mock.get_averaging_interval_range_CallInstance);
  if (Mock.get_averaging_interval_range_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_averaging_interval_range_FinalReturn;
    Mock.get_averaging_interval_range_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_averaging_interval_range_CallbackBool &&
      Mock.get_averaging_interval_range_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.get_averaging_interval_range_CallbackFunctionPointer(id, min_pai, max_pai, Mock.get_averaging_interval_range_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_get_averaging_interval_range,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_min_pai)
  {
    UNITY_SET_DETAILS(CMockString_get_averaging_interval_range,CMockString_min_pai);
    if (cmock_call_instance->Expected_min_pai == NULL)
      { UNITY_TEST_ASSERT_NULL(min_pai, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_min_pai, min_pai, cmock_call_instance->Expected_min_pai_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_max_pai)
  {
    UNITY_SET_DETAILS(CMockString_get_averaging_interval_range,CMockString_max_pai);
    if (cmock_call_instance->Expected_max_pai == NULL)
      { UNITY_TEST_ASSERT_NULL(max_pai, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_max_pai, max_pai, cmock_call_instance->Expected_max_pai_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.get_averaging_interval_range_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_averaging_interval_range_CallbackFunctionPointer(id, min_pai, max_pai, Mock.get_averaging_interval_range_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_min_pai_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(min_pai, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)min_pai, (void*)cmock_call_instance->ReturnThruPtr_min_pai_Val,
      cmock_call_instance->ReturnThruPtr_min_pai_Size);
  }
  if (cmock_call_instance->ReturnThruPtr_max_pai_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(max_pai, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)max_pai, (void*)cmock_call_instance->ReturnThruPtr_max_pai_Val,
      cmock_call_instance->ReturnThruPtr_max_pai_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_averaging_interval_range(CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* min_pai, int min_pai_Depth, uint32_t* max_pai, int max_pai_Depth);
void CMockExpectParameters_get_averaging_interval_range(CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* min_pai, int min_pai_Depth, uint32_t* max_pai, int max_pai_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  cmock_call_instance->Expected_min_pai = min_pai;
  cmock_call_instance->Expected_min_pai_Depth = min_pai_Depth;
  cmock_call_instance->IgnoreArg_min_pai = 0;
  cmock_call_instance->ReturnThruPtr_min_pai_Used = 0;
  cmock_call_instance->Expected_max_pai = max_pai;
  cmock_call_instance->Expected_max_pai_Depth = max_pai_Depth;
  cmock_call_instance->IgnoreArg_max_pai = 0;
  cmock_call_instance->ReturnThruPtr_max_pai_Used = 0;
}

void get_averaging_interval_range_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_range_CALL_INSTANCE));
  CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_range_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_range_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_range_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_averaging_interval_range_IgnoreBool = (char)1;
}

void get_averaging_interval_range_CMockStopIgnore(void)
{
  if(Mock.get_averaging_interval_range_IgnoreBool)
    Mock.get_averaging_interval_range_CallInstance = CMock_Guts_MemNext(Mock.get_averaging_interval_range_CallInstance);
  Mock.get_averaging_interval_range_IgnoreBool = (char)0;
}

void get_averaging_interval_range_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_range_CALL_INSTANCE));
  CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_range_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_range_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_range_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_averaging_interval_range_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* min_pai, uint32_t* max_pai, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_range_CALL_INSTANCE));
  CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_range_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_range_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_range_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_averaging_interval_range(cmock_call_instance, id, min_pai, 1, max_pai, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_averaging_interval_range_AddCallback(CMOCK_get_averaging_interval_range_CALLBACK Callback)
{
  Mock.get_averaging_interval_range_IgnoreBool = (char)0;
  Mock.get_averaging_interval_range_CallbackBool = (char)1;
  Mock.get_averaging_interval_range_CallbackFunctionPointer = Callback;
}

void get_averaging_interval_range_Stub(CMOCK_get_averaging_interval_range_CALLBACK Callback)
{
  Mock.get_averaging_interval_range_IgnoreBool = (char)0;
  Mock.get_averaging_interval_range_CallbackBool = (char)0;
  Mock.get_averaging_interval_range_CallbackFunctionPointer = Callback;
}

void get_averaging_interval_range_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* min_pai, int min_pai_Depth, uint32_t* max_pai, int max_pai_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_averaging_interval_range_CALL_INSTANCE));
  CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_averaging_interval_range_CallInstance = CMock_Guts_MemChain(Mock.get_averaging_interval_range_CallInstance, cmock_guts_index);
  Mock.get_averaging_interval_range_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_averaging_interval_range(cmock_call_instance, id, min_pai, min_pai_Depth, max_pai, max_pai_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_averaging_interval_range_CMockReturnMemThruPtr_min_pai(UNITY_LINE_TYPE cmock_line, uint32_t* min_pai, size_t cmock_size)
{
  CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_averaging_interval_range_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_min_pai_Used = 1;
  cmock_call_instance->ReturnThruPtr_min_pai_Val = min_pai;
  cmock_call_instance->ReturnThruPtr_min_pai_Size = cmock_size;
}

void get_averaging_interval_range_CMockReturnMemThruPtr_max_pai(UNITY_LINE_TYPE cmock_line, uint32_t* max_pai, size_t cmock_size)
{
  CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_averaging_interval_range_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_max_pai_Used = 1;
  cmock_call_instance->ReturnThruPtr_max_pai_Val = max_pai;
  cmock_call_instance->ReturnThruPtr_max_pai_Size = cmock_size;
}

void get_averaging_interval_range_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_averaging_interval_range_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void get_averaging_interval_range_CMockIgnoreArg_min_pai(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_averaging_interval_range_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_min_pai = 1;
}

void get_averaging_interval_range_CMockIgnoreArg_max_pai(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_averaging_interval_range_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_averaging_interval_range_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_averaging_interval_range_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_max_pai = 1;
}

int update(fwk_id_t id, int64_t input, int64_t* output)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_update_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_update);
  cmock_call_instance = (CMOCK_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.update_CallInstance);
  Mock.update_CallInstance = CMock_Guts_MemNext(Mock.update_CallInstance);
  if (Mock.update_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.update_FinalReturn;
    Mock.update_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.update_CallbackBool &&
      Mock.update_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.update_CallbackFunctionPointer(id, input, output, Mock.update_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_update,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_input)
  {
    UNITY_SET_DETAILS(CMockString_update,CMockString_input);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_input), (void*)(&input), sizeof(int64_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_output)
  {
    UNITY_SET_DETAILS(CMockString_update,CMockString_output);
    if (cmock_call_instance->Expected_output == NULL)
      { UNITY_TEST_ASSERT_NULL(output, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_output), (void*)(output), sizeof(int64_t), cmock_call_instance->Expected_output_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.update_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.update_CallbackFunctionPointer(id, input, output, Mock.update_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_output_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(output, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)output, (void*)cmock_call_instance->ReturnThruPtr_output_Val,
      cmock_call_instance->ReturnThruPtr_output_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_update(CMOCK_update_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, int64_t input, int64_t* output, int output_Depth);
void CMockExpectParameters_update(CMOCK_update_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, int64_t input, int64_t* output, int output_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  memcpy((void*)(&cmock_call_instance->Expected_input), (void*)(&input),
         sizeof(int64_t[sizeof(input) == sizeof(int64_t) ? 1 : -1])); /* add int64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_input = 0;
  cmock_call_instance->Expected_output = output;
  cmock_call_instance->Expected_output_Depth = output_Depth;
  cmock_call_instance->IgnoreArg_output = 0;
  cmock_call_instance->ReturnThruPtr_output_Used = 0;
}

void update_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_update_CALL_INSTANCE));
  CMOCK_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.update_CallInstance = CMock_Guts_MemChain(Mock.update_CallInstance, cmock_guts_index);
  Mock.update_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.update_IgnoreBool = (char)1;
}

void update_CMockStopIgnore(void)
{
  if(Mock.update_IgnoreBool)
    Mock.update_CallInstance = CMock_Guts_MemNext(Mock.update_CallInstance);
  Mock.update_IgnoreBool = (char)0;
}

void update_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_update_CALL_INSTANCE));
  CMOCK_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.update_CallInstance = CMock_Guts_MemChain(Mock.update_CallInstance, cmock_guts_index);
  Mock.update_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void update_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, int64_t input, int64_t* output, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_update_CALL_INSTANCE));
  CMOCK_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.update_CallInstance = CMock_Guts_MemChain(Mock.update_CallInstance, cmock_guts_index);
  Mock.update_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_update(cmock_call_instance, id, input, output, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void update_AddCallback(CMOCK_update_CALLBACK Callback)
{
  Mock.update_IgnoreBool = (char)0;
  Mock.update_CallbackBool = (char)1;
  Mock.update_CallbackFunctionPointer = Callback;
}

void update_Stub(CMOCK_update_CALLBACK Callback)
{
  Mock.update_IgnoreBool = (char)0;
  Mock.update_CallbackBool = (char)0;
  Mock.update_CallbackFunctionPointer = Callback;
}

void update_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, int64_t input, int64_t* output, int output_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_update_CALL_INSTANCE));
  CMOCK_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.update_CallInstance = CMock_Guts_MemChain(Mock.update_CallInstance, cmock_guts_index);
  Mock.update_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_update(cmock_call_instance, id, input, output, output_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void update_CMockReturnMemThruPtr_output(UNITY_LINE_TYPE cmock_line, int64_t* output, size_t cmock_size)
{
  CMOCK_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.update_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_output_Used = 1;
  cmock_call_instance->ReturnThruPtr_output_Val = output;
  cmock_call_instance->ReturnThruPtr_output_Size = cmock_size;
}

void update_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.update_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void update_CMockIgnoreArg_input(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.update_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_input = 1;
}

void update_CMockIgnoreArg_output(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.update_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_output = 1;
}

int set_point(fwk_id_t id, int64_t input)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_set_point_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_set_point);
  cmock_call_instance = (CMOCK_set_point_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.set_point_CallInstance);
  Mock.set_point_CallInstance = CMock_Guts_MemNext(Mock.set_point_CallInstance);
  if (Mock.set_point_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.set_point_FinalReturn;
    Mock.set_point_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.set_point_CallbackBool &&
      Mock.set_point_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.set_point_CallbackFunctionPointer(id, input, Mock.set_point_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_set_point,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_input)
  {
    UNITY_SET_DETAILS(CMockString_set_point,CMockString_input);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_input), (void*)(&input), sizeof(int64_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.set_point_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.set_point_CallbackFunctionPointer(id, input, Mock.set_point_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_set_point(CMOCK_set_point_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, int64_t input);
void CMockExpectParameters_set_point(CMOCK_set_point_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, int64_t input)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  memcpy((void*)(&cmock_call_instance->Expected_input), (void*)(&input),
         sizeof(int64_t[sizeof(input) == sizeof(int64_t) ? 1 : -1])); /* add int64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_input = 0;
}

void set_point_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_point_CALL_INSTANCE));
  CMOCK_set_point_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_point_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_point_CallInstance = CMock_Guts_MemChain(Mock.set_point_CallInstance, cmock_guts_index);
  Mock.set_point_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.set_point_IgnoreBool = (char)1;
}

void set_point_CMockStopIgnore(void)
{
  if(Mock.set_point_IgnoreBool)
    Mock.set_point_CallInstance = CMock_Guts_MemNext(Mock.set_point_CallInstance);
  Mock.set_point_IgnoreBool = (char)0;
}

void set_point_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_point_CALL_INSTANCE));
  CMOCK_set_point_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_point_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_point_CallInstance = CMock_Guts_MemChain(Mock.set_point_CallInstance, cmock_guts_index);
  Mock.set_point_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void set_point_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, int64_t input, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_point_CALL_INSTANCE));
  CMOCK_set_point_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_point_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_point_CallInstance = CMock_Guts_MemChain(Mock.set_point_CallInstance, cmock_guts_index);
  Mock.set_point_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_set_point(cmock_call_instance, id, input);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void set_point_AddCallback(CMOCK_set_point_CALLBACK Callback)
{
  Mock.set_point_IgnoreBool = (char)0;
  Mock.set_point_CallbackBool = (char)1;
  Mock.set_point_CallbackFunctionPointer = Callback;
}

void set_point_Stub(CMOCK_set_point_CALLBACK Callback)
{
  Mock.set_point_IgnoreBool = (char)0;
  Mock.set_point_CallbackBool = (char)0;
  Mock.set_point_CallbackFunctionPointer = Callback;
}

void set_point_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_set_point_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_point_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.set_point_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void set_point_CMockIgnoreArg_input(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_set_point_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_point_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.set_point_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_input = 1;
}
