/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_power_distributor_extra.h"

static const char* CMockString_id = "id";
static const char* CMockString_mock_get_power_limit = "mock_get_power_limit";
static const char* CMockString_mock_set_power_demand = "mock_set_power_demand";
static const char* CMockString_mock_set_power_limit = "mock_set_power_limit";
static const char* CMockString_power_demand = "power_demand";
static const char* CMockString_power_limit = "power_limit";

typedef struct _CMOCK_mock_get_power_limit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  uint32_t* Expected_power_limit;
  int Expected_power_limit_Depth;
  char ReturnThruPtr_power_limit_Used;
  uint32_t* ReturnThruPtr_power_limit_Val;
  size_t ReturnThruPtr_power_limit_Size;
  char IgnoreArg_id;
  char IgnoreArg_power_limit;

} CMOCK_mock_get_power_limit_CALL_INSTANCE;

typedef struct _CMOCK_mock_set_power_limit_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  uint32_t Expected_power_limit;
  char IgnoreArg_id;
  char IgnoreArg_power_limit;

} CMOCK_mock_set_power_limit_CALL_INSTANCE;

typedef struct _CMOCK_mock_set_power_demand_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  uint32_t Expected_power_demand;
  char IgnoreArg_id;
  char IgnoreArg_power_demand;

} CMOCK_mock_set_power_demand_CALL_INSTANCE;

static struct Mockmod_power_distributor_extraInstance
{
  char mock_get_power_limit_IgnoreBool;
  int mock_get_power_limit_FinalReturn;
  char mock_get_power_limit_CallbackBool;
  CMOCK_mock_get_power_limit_CALLBACK mock_get_power_limit_CallbackFunctionPointer;
  int mock_get_power_limit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE mock_get_power_limit_CallInstance;
  char mock_set_power_limit_IgnoreBool;
  int mock_set_power_limit_FinalReturn;
  char mock_set_power_limit_CallbackBool;
  CMOCK_mock_set_power_limit_CALLBACK mock_set_power_limit_CallbackFunctionPointer;
  int mock_set_power_limit_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE mock_set_power_limit_CallInstance;
  char mock_set_power_demand_IgnoreBool;
  int mock_set_power_demand_FinalReturn;
  char mock_set_power_demand_CallbackBool;
  CMOCK_mock_set_power_demand_CALLBACK mock_set_power_demand_CallbackFunctionPointer;
  int mock_set_power_demand_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE mock_set_power_demand_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_power_distributor_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.mock_get_power_limit_CallInstance;
  if (Mock.mock_get_power_limit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mock_get_power_limit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.mock_get_power_limit_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.mock_set_power_limit_CallInstance;
  if (Mock.mock_set_power_limit_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mock_set_power_limit);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.mock_set_power_limit_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.mock_set_power_demand_CallInstance;
  if (Mock.mock_set_power_demand_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mock_set_power_demand);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.mock_set_power_demand_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_power_distributor_extra_Init(void)
{
  Mockmod_power_distributor_extra_Destroy();
}

void Mockmod_power_distributor_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int mock_get_power_limit(fwk_id_t id, uint32_t* power_limit)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mock_get_power_limit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mock_get_power_limit);
  cmock_call_instance = (CMOCK_mock_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mock_get_power_limit_CallInstance);
  Mock.mock_get_power_limit_CallInstance = CMock_Guts_MemNext(Mock.mock_get_power_limit_CallInstance);
  if (Mock.mock_get_power_limit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.mock_get_power_limit_FinalReturn;
    Mock.mock_get_power_limit_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.mock_get_power_limit_CallbackBool &&
      Mock.mock_get_power_limit_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.mock_get_power_limit_CallbackFunctionPointer(id, power_limit, Mock.mock_get_power_limit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_mock_get_power_limit,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_power_limit)
  {
    UNITY_SET_DETAILS(CMockString_mock_get_power_limit,CMockString_power_limit);
    if (cmock_call_instance->Expected_power_limit == NULL)
      { UNITY_TEST_ASSERT_NULL(power_limit, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_power_limit, power_limit, cmock_call_instance->Expected_power_limit_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.mock_get_power_limit_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.mock_get_power_limit_CallbackFunctionPointer(id, power_limit, Mock.mock_get_power_limit_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_power_limit_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(power_limit, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)power_limit, (void*)cmock_call_instance->ReturnThruPtr_power_limit_Val,
      cmock_call_instance->ReturnThruPtr_power_limit_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mock_get_power_limit(CMOCK_mock_get_power_limit_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* power_limit, int power_limit_Depth);
void CMockExpectParameters_mock_get_power_limit(CMOCK_mock_get_power_limit_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t* power_limit, int power_limit_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  cmock_call_instance->Expected_power_limit = power_limit;
  cmock_call_instance->Expected_power_limit_Depth = power_limit_Depth;
  cmock_call_instance->IgnoreArg_power_limit = 0;
  cmock_call_instance->ReturnThruPtr_power_limit_Used = 0;
}

void mock_get_power_limit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_get_power_limit_CALL_INSTANCE));
  CMOCK_mock_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_get_power_limit_CallInstance = CMock_Guts_MemChain(Mock.mock_get_power_limit_CallInstance, cmock_guts_index);
  Mock.mock_get_power_limit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.mock_get_power_limit_IgnoreBool = (char)1;
}

void mock_get_power_limit_CMockStopIgnore(void)
{
  if(Mock.mock_get_power_limit_IgnoreBool)
    Mock.mock_get_power_limit_CallInstance = CMock_Guts_MemNext(Mock.mock_get_power_limit_CallInstance);
  Mock.mock_get_power_limit_IgnoreBool = (char)0;
}

void mock_get_power_limit_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_get_power_limit_CALL_INSTANCE));
  CMOCK_mock_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_get_power_limit_CallInstance = CMock_Guts_MemChain(Mock.mock_get_power_limit_CallInstance, cmock_guts_index);
  Mock.mock_get_power_limit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void mock_get_power_limit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* power_limit, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_get_power_limit_CALL_INSTANCE));
  CMOCK_mock_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_get_power_limit_CallInstance = CMock_Guts_MemChain(Mock.mock_get_power_limit_CallInstance, cmock_guts_index);
  Mock.mock_get_power_limit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mock_get_power_limit(cmock_call_instance, id, power_limit, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mock_get_power_limit_AddCallback(CMOCK_mock_get_power_limit_CALLBACK Callback)
{
  Mock.mock_get_power_limit_IgnoreBool = (char)0;
  Mock.mock_get_power_limit_CallbackBool = (char)1;
  Mock.mock_get_power_limit_CallbackFunctionPointer = Callback;
}

void mock_get_power_limit_Stub(CMOCK_mock_get_power_limit_CALLBACK Callback)
{
  Mock.mock_get_power_limit_IgnoreBool = (char)0;
  Mock.mock_get_power_limit_CallbackBool = (char)0;
  Mock.mock_get_power_limit_CallbackFunctionPointer = Callback;
}

void mock_get_power_limit_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t* power_limit, int power_limit_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_get_power_limit_CALL_INSTANCE));
  CMOCK_mock_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_get_power_limit_CallInstance = CMock_Guts_MemChain(Mock.mock_get_power_limit_CallInstance, cmock_guts_index);
  Mock.mock_get_power_limit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mock_get_power_limit(cmock_call_instance, id, power_limit, power_limit_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mock_get_power_limit_CMockReturnMemThruPtr_power_limit(UNITY_LINE_TYPE cmock_line, uint32_t* power_limit, size_t cmock_size)
{
  CMOCK_mock_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_get_power_limit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_power_limit_Used = 1;
  cmock_call_instance->ReturnThruPtr_power_limit_Val = power_limit;
  cmock_call_instance->ReturnThruPtr_power_limit_Size = cmock_size;
}

void mock_get_power_limit_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_get_power_limit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void mock_get_power_limit_CMockIgnoreArg_power_limit(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_get_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_get_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_get_power_limit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_power_limit = 1;
}

int mock_set_power_limit(fwk_id_t id, uint32_t power_limit)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mock_set_power_limit_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mock_set_power_limit);
  cmock_call_instance = (CMOCK_mock_set_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mock_set_power_limit_CallInstance);
  Mock.mock_set_power_limit_CallInstance = CMock_Guts_MemNext(Mock.mock_set_power_limit_CallInstance);
  if (Mock.mock_set_power_limit_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.mock_set_power_limit_FinalReturn;
    Mock.mock_set_power_limit_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.mock_set_power_limit_CallbackBool &&
      Mock.mock_set_power_limit_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.mock_set_power_limit_CallbackFunctionPointer(id, power_limit, Mock.mock_set_power_limit_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_mock_set_power_limit,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_power_limit)
  {
    UNITY_SET_DETAILS(CMockString_mock_set_power_limit,CMockString_power_limit);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_power_limit, power_limit, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.mock_set_power_limit_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.mock_set_power_limit_CallbackFunctionPointer(id, power_limit, Mock.mock_set_power_limit_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mock_set_power_limit(CMOCK_mock_set_power_limit_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t power_limit);
void CMockExpectParameters_mock_set_power_limit(CMOCK_mock_set_power_limit_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t power_limit)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  cmock_call_instance->Expected_power_limit = power_limit;
  cmock_call_instance->IgnoreArg_power_limit = 0;
}

void mock_set_power_limit_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_set_power_limit_CALL_INSTANCE));
  CMOCK_mock_set_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_set_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_set_power_limit_CallInstance = CMock_Guts_MemChain(Mock.mock_set_power_limit_CallInstance, cmock_guts_index);
  Mock.mock_set_power_limit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.mock_set_power_limit_IgnoreBool = (char)1;
}

void mock_set_power_limit_CMockStopIgnore(void)
{
  if(Mock.mock_set_power_limit_IgnoreBool)
    Mock.mock_set_power_limit_CallInstance = CMock_Guts_MemNext(Mock.mock_set_power_limit_CallInstance);
  Mock.mock_set_power_limit_IgnoreBool = (char)0;
}

void mock_set_power_limit_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_set_power_limit_CALL_INSTANCE));
  CMOCK_mock_set_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_set_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_set_power_limit_CallInstance = CMock_Guts_MemChain(Mock.mock_set_power_limit_CallInstance, cmock_guts_index);
  Mock.mock_set_power_limit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void mock_set_power_limit_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t power_limit, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_set_power_limit_CALL_INSTANCE));
  CMOCK_mock_set_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_set_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_set_power_limit_CallInstance = CMock_Guts_MemChain(Mock.mock_set_power_limit_CallInstance, cmock_guts_index);
  Mock.mock_set_power_limit_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mock_set_power_limit(cmock_call_instance, id, power_limit);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mock_set_power_limit_AddCallback(CMOCK_mock_set_power_limit_CALLBACK Callback)
{
  Mock.mock_set_power_limit_IgnoreBool = (char)0;
  Mock.mock_set_power_limit_CallbackBool = (char)1;
  Mock.mock_set_power_limit_CallbackFunctionPointer = Callback;
}

void mock_set_power_limit_Stub(CMOCK_mock_set_power_limit_CALLBACK Callback)
{
  Mock.mock_set_power_limit_IgnoreBool = (char)0;
  Mock.mock_set_power_limit_CallbackBool = (char)0;
  Mock.mock_set_power_limit_CallbackFunctionPointer = Callback;
}

void mock_set_power_limit_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_set_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_set_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_set_power_limit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void mock_set_power_limit_CMockIgnoreArg_power_limit(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_set_power_limit_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_set_power_limit_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_set_power_limit_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_power_limit = 1;
}

int mock_set_power_demand(fwk_id_t id, uint32_t power_demand)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mock_set_power_demand_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mock_set_power_demand);
  cmock_call_instance = (CMOCK_mock_set_power_demand_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mock_set_power_demand_CallInstance);
  Mock.mock_set_power_demand_CallInstance = CMock_Guts_MemNext(Mock.mock_set_power_demand_CallInstance);
  if (Mock.mock_set_power_demand_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.mock_set_power_demand_FinalReturn;
    Mock.mock_set_power_demand_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.mock_set_power_demand_CallbackBool &&
      Mock.mock_set_power_demand_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.mock_set_power_demand_CallbackFunctionPointer(id, power_demand, Mock.mock_set_power_demand_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_mock_set_power_demand,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_power_demand)
  {
    UNITY_SET_DETAILS(CMockString_mock_set_power_demand,CMockString_power_demand);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_power_demand, power_demand, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.mock_set_power_demand_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.mock_set_power_demand_CallbackFunctionPointer(id, power_demand, Mock.mock_set_power_demand_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mock_set_power_demand(CMOCK_mock_set_power_demand_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t power_demand);
void CMockExpectParameters_mock_set_power_demand(CMOCK_mock_set_power_demand_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, uint32_t power_demand)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  cmock_call_instance->Expected_power_demand = power_demand;
  cmock_call_instance->IgnoreArg_power_demand = 0;
}

void mock_set_power_demand_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_set_power_demand_CALL_INSTANCE));
  CMOCK_mock_set_power_demand_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_set_power_demand_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_set_power_demand_CallInstance = CMock_Guts_MemChain(Mock.mock_set_power_demand_CallInstance, cmock_guts_index);
  Mock.mock_set_power_demand_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.mock_set_power_demand_IgnoreBool = (char)1;
}

void mock_set_power_demand_CMockStopIgnore(void)
{
  if(Mock.mock_set_power_demand_IgnoreBool)
    Mock.mock_set_power_demand_CallInstance = CMock_Guts_MemNext(Mock.mock_set_power_demand_CallInstance);
  Mock.mock_set_power_demand_IgnoreBool = (char)0;
}

void mock_set_power_demand_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_set_power_demand_CALL_INSTANCE));
  CMOCK_mock_set_power_demand_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_set_power_demand_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_set_power_demand_CallInstance = CMock_Guts_MemChain(Mock.mock_set_power_demand_CallInstance, cmock_guts_index);
  Mock.mock_set_power_demand_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void mock_set_power_demand_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, uint32_t power_demand, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mock_set_power_demand_CALL_INSTANCE));
  CMOCK_mock_set_power_demand_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_set_power_demand_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mock_set_power_demand_CallInstance = CMock_Guts_MemChain(Mock.mock_set_power_demand_CallInstance, cmock_guts_index);
  Mock.mock_set_power_demand_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mock_set_power_demand(cmock_call_instance, id, power_demand);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mock_set_power_demand_AddCallback(CMOCK_mock_set_power_demand_CALLBACK Callback)
{
  Mock.mock_set_power_demand_IgnoreBool = (char)0;
  Mock.mock_set_power_demand_CallbackBool = (char)1;
  Mock.mock_set_power_demand_CallbackFunctionPointer = Callback;
}

void mock_set_power_demand_Stub(CMOCK_mock_set_power_demand_CALLBACK Callback)
{
  Mock.mock_set_power_demand_IgnoreBool = (char)0;
  Mock.mock_set_power_demand_CallbackBool = (char)0;
  Mock.mock_set_power_demand_CallbackFunctionPointer = Callback;
}

void mock_set_power_demand_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_set_power_demand_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_set_power_demand_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_set_power_demand_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void mock_set_power_demand_CMockIgnoreArg_power_demand(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mock_set_power_demand_CALL_INSTANCE* cmock_call_instance = (CMOCK_mock_set_power_demand_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mock_set_power_demand_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_power_demand = 1;
}

