/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_perf_controller_extra.h"

static const char* CMockString_domain_apply_performance_granted_stub = "domain_apply_performance_granted_stub";
static const char* CMockString_domain_ctx = "domain_ctx";
static const char* CMockString_cookie = "cookie";
static const char* CMockString_domain_id = "domain_id";
static const char* CMockString_driver_set_performance_level = "driver_set_performance_level";
static const char* CMockString_get_limiters_min_power_limit_stub = "get_limiters_min_power_limit_stub";
static const char* CMockString_model_id = "model_id";
static const char* CMockString_performance_level = "performance_level";
static const char* CMockString_power = "power";
static const char* CMockString_power_to_performance = "power_to_performance";

typedef struct _CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint32_t ReturnVal;
  struct mod_perf_controller_domain_ctx* Expected_domain_ctx;
  int Expected_domain_ctx_Depth;
  char ReturnThruPtr_domain_ctx_Used;
  struct mod_perf_controller_domain_ctx* ReturnThruPtr_domain_ctx_Val;
  size_t ReturnThruPtr_domain_ctx_Size;
  char IgnoreArg_domain_ctx;

} CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE;

typedef struct _CMOCK_power_to_performance_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_model_id;
  uint32_t Expected_power;
  uint32_t* Expected_performance_level;
  int Expected_performance_level_Depth;
  char ReturnThruPtr_performance_level_Used;
  uint32_t* ReturnThruPtr_performance_level_Val;
  size_t ReturnThruPtr_performance_level_Size;
  char IgnoreArg_model_id;
  char IgnoreArg_power;
  char IgnoreArg_performance_level;

} CMOCK_power_to_performance_CALL_INSTANCE;

typedef struct _CMOCK_driver_set_performance_level_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_domain_id;
  uintptr_t Expected_cookie;
  uint32_t Expected_performance_level;
  char IgnoreArg_domain_id;
  char IgnoreArg_cookie;
  char IgnoreArg_performance_level;

} CMOCK_driver_set_performance_level_CALL_INSTANCE;

typedef struct _CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  struct mod_perf_controller_domain_ctx* Expected_domain_ctx;
  int Expected_domain_ctx_Depth;
  char ReturnThruPtr_domain_ctx_Used;
  struct mod_perf_controller_domain_ctx* ReturnThruPtr_domain_ctx_Val;
  size_t ReturnThruPtr_domain_ctx_Size;
  char IgnoreArg_domain_ctx;

} CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE;

static struct Mockmod_perf_controller_extraInstance
{
  char get_limiters_min_power_limit_stub_IgnoreBool;
  uint32_t get_limiters_min_power_limit_stub_FinalReturn;
  char get_limiters_min_power_limit_stub_CallbackBool;
  CMOCK_get_limiters_min_power_limit_stub_CALLBACK get_limiters_min_power_limit_stub_CallbackFunctionPointer;
  int get_limiters_min_power_limit_stub_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_limiters_min_power_limit_stub_CallInstance;
  char power_to_performance_IgnoreBool;
  int power_to_performance_FinalReturn;
  char power_to_performance_CallbackBool;
  CMOCK_power_to_performance_CALLBACK power_to_performance_CallbackFunctionPointer;
  int power_to_performance_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE power_to_performance_CallInstance;
  char driver_set_performance_level_IgnoreBool;
  int driver_set_performance_level_FinalReturn;
  char driver_set_performance_level_CallbackBool;
  CMOCK_driver_set_performance_level_CALLBACK driver_set_performance_level_CallbackFunctionPointer;
  int driver_set_performance_level_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE driver_set_performance_level_CallInstance;
  char domain_apply_performance_granted_stub_IgnoreBool;
  int domain_apply_performance_granted_stub_FinalReturn;
  char domain_apply_performance_granted_stub_CallbackBool;
  CMOCK_domain_apply_performance_granted_stub_CALLBACK domain_apply_performance_granted_stub_CallbackFunctionPointer;
  int domain_apply_performance_granted_stub_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE domain_apply_performance_granted_stub_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_perf_controller_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.get_limiters_min_power_limit_stub_CallInstance;
  if (Mock.get_limiters_min_power_limit_stub_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_limiters_min_power_limit_stub);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_limiters_min_power_limit_stub_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.power_to_performance_CallInstance;
  if (Mock.power_to_performance_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_power_to_performance);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.power_to_performance_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.driver_set_performance_level_CallInstance;
  if (Mock.driver_set_performance_level_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_driver_set_performance_level);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.driver_set_performance_level_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.domain_apply_performance_granted_stub_CallInstance;
  if (Mock.domain_apply_performance_granted_stub_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_domain_apply_performance_granted_stub);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.domain_apply_performance_granted_stub_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_perf_controller_extra_Init(void)
{
  Mockmod_perf_controller_extra_Destroy();
}

void Mockmod_perf_controller_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint32_t get_limiters_min_power_limit_stub(struct mod_perf_controller_domain_ctx* domain_ctx)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_limiters_min_power_limit_stub);
  cmock_call_instance = (CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_limiters_min_power_limit_stub_CallInstance);
  Mock.get_limiters_min_power_limit_stub_CallInstance = CMock_Guts_MemNext(Mock.get_limiters_min_power_limit_stub_CallInstance);
  if (Mock.get_limiters_min_power_limit_stub_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_limiters_min_power_limit_stub_FinalReturn;
    Mock.get_limiters_min_power_limit_stub_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_limiters_min_power_limit_stub_CallbackBool &&
      Mock.get_limiters_min_power_limit_stub_CallbackFunctionPointer != NULL)
  {
    uint32_t cmock_cb_ret = Mock.get_limiters_min_power_limit_stub_CallbackFunctionPointer(domain_ctx, Mock.get_limiters_min_power_limit_stub_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_domain_ctx)
  {
    UNITY_SET_DETAILS(CMockString_get_limiters_min_power_limit_stub,CMockString_domain_ctx);
    if (cmock_call_instance->Expected_domain_ctx == NULL)
      { UNITY_TEST_ASSERT_NULL(domain_ctx, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_domain_ctx), (void*)(domain_ctx), sizeof(struct mod_perf_controller_domain_ctx), cmock_call_instance->Expected_domain_ctx_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.get_limiters_min_power_limit_stub_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_limiters_min_power_limit_stub_CallbackFunctionPointer(domain_ctx, Mock.get_limiters_min_power_limit_stub_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_domain_ctx_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(domain_ctx, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)domain_ctx, (void*)cmock_call_instance->ReturnThruPtr_domain_ctx_Val,
      cmock_call_instance->ReturnThruPtr_domain_ctx_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_limiters_min_power_limit_stub(CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE* cmock_call_instance, struct mod_perf_controller_domain_ctx* domain_ctx, int domain_ctx_Depth);
void CMockExpectParameters_get_limiters_min_power_limit_stub(CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE* cmock_call_instance, struct mod_perf_controller_domain_ctx* domain_ctx, int domain_ctx_Depth)
{
  cmock_call_instance->Expected_domain_ctx = domain_ctx;
  cmock_call_instance->Expected_domain_ctx_Depth = domain_ctx_Depth;
  cmock_call_instance->IgnoreArg_domain_ctx = 0;
  cmock_call_instance->ReturnThruPtr_domain_ctx_Used = 0;
}

void get_limiters_min_power_limit_stub_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE));
  CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_limiters_min_power_limit_stub_CallInstance = CMock_Guts_MemChain(Mock.get_limiters_min_power_limit_stub_CallInstance, cmock_guts_index);
  Mock.get_limiters_min_power_limit_stub_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_limiters_min_power_limit_stub_IgnoreBool = (char)1;
}

void get_limiters_min_power_limit_stub_CMockStopIgnore(void)
{
  if(Mock.get_limiters_min_power_limit_stub_IgnoreBool)
    Mock.get_limiters_min_power_limit_stub_CallInstance = CMock_Guts_MemNext(Mock.get_limiters_min_power_limit_stub_CallInstance);
  Mock.get_limiters_min_power_limit_stub_IgnoreBool = (char)0;
}

void get_limiters_min_power_limit_stub_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE));
  CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_limiters_min_power_limit_stub_CallInstance = CMock_Guts_MemChain(Mock.get_limiters_min_power_limit_stub_CallInstance, cmock_guts_index);
  Mock.get_limiters_min_power_limit_stub_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_limiters_min_power_limit_stub_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_perf_controller_domain_ctx* domain_ctx, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE));
  CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_limiters_min_power_limit_stub_CallInstance = CMock_Guts_MemChain(Mock.get_limiters_min_power_limit_stub_CallInstance, cmock_guts_index);
  Mock.get_limiters_min_power_limit_stub_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_limiters_min_power_limit_stub(cmock_call_instance, domain_ctx, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_limiters_min_power_limit_stub_AddCallback(CMOCK_get_limiters_min_power_limit_stub_CALLBACK Callback)
{
  Mock.get_limiters_min_power_limit_stub_IgnoreBool = (char)0;
  Mock.get_limiters_min_power_limit_stub_CallbackBool = (char)1;
  Mock.get_limiters_min_power_limit_stub_CallbackFunctionPointer = Callback;
}

void get_limiters_min_power_limit_stub_Stub(CMOCK_get_limiters_min_power_limit_stub_CALLBACK Callback)
{
  Mock.get_limiters_min_power_limit_stub_IgnoreBool = (char)0;
  Mock.get_limiters_min_power_limit_stub_CallbackBool = (char)0;
  Mock.get_limiters_min_power_limit_stub_CallbackFunctionPointer = Callback;
}

void get_limiters_min_power_limit_stub_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_perf_controller_domain_ctx* domain_ctx, int domain_ctx_Depth, uint32_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE));
  CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_limiters_min_power_limit_stub_CallInstance = CMock_Guts_MemChain(Mock.get_limiters_min_power_limit_stub_CallInstance, cmock_guts_index);
  Mock.get_limiters_min_power_limit_stub_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_limiters_min_power_limit_stub(cmock_call_instance, domain_ctx, domain_ctx_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_limiters_min_power_limit_stub_CMockReturnMemThruPtr_domain_ctx(UNITY_LINE_TYPE cmock_line, struct mod_perf_controller_domain_ctx* domain_ctx, size_t cmock_size)
{
  CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_limiters_min_power_limit_stub_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_domain_ctx_Used = 1;
  cmock_call_instance->ReturnThruPtr_domain_ctx_Val = domain_ctx;
  cmock_call_instance->ReturnThruPtr_domain_ctx_Size = cmock_size;
}

void get_limiters_min_power_limit_stub_CMockIgnoreArg_domain_ctx(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_limiters_min_power_limit_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_limiters_min_power_limit_stub_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_domain_ctx = 1;
}

int power_to_performance(fwk_id_t model_id, uint32_t power, uint32_t* performance_level)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_power_to_performance_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_power_to_performance);
  cmock_call_instance = (CMOCK_power_to_performance_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.power_to_performance_CallInstance);
  Mock.power_to_performance_CallInstance = CMock_Guts_MemNext(Mock.power_to_performance_CallInstance);
  if (Mock.power_to_performance_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.power_to_performance_FinalReturn;
    Mock.power_to_performance_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.power_to_performance_CallbackBool &&
      Mock.power_to_performance_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.power_to_performance_CallbackFunctionPointer(model_id, power, performance_level, Mock.power_to_performance_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_model_id)
  {
    UNITY_SET_DETAILS(CMockString_power_to_performance,CMockString_model_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_model_id), (void*)(&model_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_power)
  {
    UNITY_SET_DETAILS(CMockString_power_to_performance,CMockString_power);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_power, power, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_performance_level)
  {
    UNITY_SET_DETAILS(CMockString_power_to_performance,CMockString_performance_level);
    if (cmock_call_instance->Expected_performance_level == NULL)
      { UNITY_TEST_ASSERT_NULL(performance_level, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_performance_level, performance_level, cmock_call_instance->Expected_performance_level_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.power_to_performance_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.power_to_performance_CallbackFunctionPointer(model_id, power, performance_level, Mock.power_to_performance_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_performance_level_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(performance_level, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)performance_level, (void*)cmock_call_instance->ReturnThruPtr_performance_level_Val,
      cmock_call_instance->ReturnThruPtr_performance_level_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_power_to_performance(CMOCK_power_to_performance_CALL_INSTANCE* cmock_call_instance, fwk_id_t model_id, uint32_t power, uint32_t* performance_level, int performance_level_Depth);
void CMockExpectParameters_power_to_performance(CMOCK_power_to_performance_CALL_INSTANCE* cmock_call_instance, fwk_id_t model_id, uint32_t power, uint32_t* performance_level, int performance_level_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_model_id), (void*)(&model_id),
         sizeof(fwk_id_t[sizeof(model_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_model_id = 0;
  cmock_call_instance->Expected_power = power;
  cmock_call_instance->IgnoreArg_power = 0;
  cmock_call_instance->Expected_performance_level = performance_level;
  cmock_call_instance->Expected_performance_level_Depth = performance_level_Depth;
  cmock_call_instance->IgnoreArg_performance_level = 0;
  cmock_call_instance->ReturnThruPtr_performance_level_Used = 0;
}

void power_to_performance_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_power_to_performance_CALL_INSTANCE));
  CMOCK_power_to_performance_CALL_INSTANCE* cmock_call_instance = (CMOCK_power_to_performance_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.power_to_performance_CallInstance = CMock_Guts_MemChain(Mock.power_to_performance_CallInstance, cmock_guts_index);
  Mock.power_to_performance_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.power_to_performance_IgnoreBool = (char)1;
}

void power_to_performance_CMockStopIgnore(void)
{
  if(Mock.power_to_performance_IgnoreBool)
    Mock.power_to_performance_CallInstance = CMock_Guts_MemNext(Mock.power_to_performance_CallInstance);
  Mock.power_to_performance_IgnoreBool = (char)0;
}

void power_to_performance_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_power_to_performance_CALL_INSTANCE));
  CMOCK_power_to_performance_CALL_INSTANCE* cmock_call_instance = (CMOCK_power_to_performance_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.power_to_performance_CallInstance = CMock_Guts_MemChain(Mock.power_to_performance_CallInstance, cmock_guts_index);
  Mock.power_to_performance_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void power_to_performance_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t model_id, uint32_t power, uint32_t* performance_level, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_power_to_performance_CALL_INSTANCE));
  CMOCK_power_to_performance_CALL_INSTANCE* cmock_call_instance = (CMOCK_power_to_performance_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.power_to_performance_CallInstance = CMock_Guts_MemChain(Mock.power_to_performance_CallInstance, cmock_guts_index);
  Mock.power_to_performance_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_power_to_performance(cmock_call_instance, model_id, power, performance_level, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void power_to_performance_AddCallback(CMOCK_power_to_performance_CALLBACK Callback)
{
  Mock.power_to_performance_IgnoreBool = (char)0;
  Mock.power_to_performance_CallbackBool = (char)1;
  Mock.power_to_performance_CallbackFunctionPointer = Callback;
}

void power_to_performance_Stub(CMOCK_power_to_performance_CALLBACK Callback)
{
  Mock.power_to_performance_IgnoreBool = (char)0;
  Mock.power_to_performance_CallbackBool = (char)0;
  Mock.power_to_performance_CallbackFunctionPointer = Callback;
}

void power_to_performance_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t model_id, uint32_t power, uint32_t* performance_level, int performance_level_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_power_to_performance_CALL_INSTANCE));
  CMOCK_power_to_performance_CALL_INSTANCE* cmock_call_instance = (CMOCK_power_to_performance_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.power_to_performance_CallInstance = CMock_Guts_MemChain(Mock.power_to_performance_CallInstance, cmock_guts_index);
  Mock.power_to_performance_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_power_to_performance(cmock_call_instance, model_id, power, performance_level, performance_level_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void power_to_performance_CMockReturnMemThruPtr_performance_level(UNITY_LINE_TYPE cmock_line, uint32_t* performance_level, size_t cmock_size)
{
  CMOCK_power_to_performance_CALL_INSTANCE* cmock_call_instance = (CMOCK_power_to_performance_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.power_to_performance_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_performance_level_Used = 1;
  cmock_call_instance->ReturnThruPtr_performance_level_Val = performance_level;
  cmock_call_instance->ReturnThruPtr_performance_level_Size = cmock_size;
}

void power_to_performance_CMockIgnoreArg_model_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_power_to_performance_CALL_INSTANCE* cmock_call_instance = (CMOCK_power_to_performance_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.power_to_performance_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_model_id = 1;
}

void power_to_performance_CMockIgnoreArg_power(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_power_to_performance_CALL_INSTANCE* cmock_call_instance = (CMOCK_power_to_performance_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.power_to_performance_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_power = 1;
}

void power_to_performance_CMockIgnoreArg_performance_level(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_power_to_performance_CALL_INSTANCE* cmock_call_instance = (CMOCK_power_to_performance_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.power_to_performance_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_performance_level = 1;
}

int driver_set_performance_level(fwk_id_t domain_id, uintptr_t cookie, uint32_t performance_level)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_driver_set_performance_level_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_driver_set_performance_level);
  cmock_call_instance = (CMOCK_driver_set_performance_level_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.driver_set_performance_level_CallInstance);
  Mock.driver_set_performance_level_CallInstance = CMock_Guts_MemNext(Mock.driver_set_performance_level_CallInstance);
  if (Mock.driver_set_performance_level_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.driver_set_performance_level_FinalReturn;
    Mock.driver_set_performance_level_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.driver_set_performance_level_CallbackBool &&
      Mock.driver_set_performance_level_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.driver_set_performance_level_CallbackFunctionPointer(domain_id, cookie, performance_level, Mock.driver_set_performance_level_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_domain_id)
  {
    UNITY_SET_DETAILS(CMockString_driver_set_performance_level,CMockString_domain_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_domain_id), (void*)(&domain_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_cookie)
  {
    UNITY_SET_DETAILS(CMockString_driver_set_performance_level,CMockString_cookie);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cookie), (void*)(&cookie), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_performance_level)
  {
    UNITY_SET_DETAILS(CMockString_driver_set_performance_level,CMockString_performance_level);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_performance_level, performance_level, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.driver_set_performance_level_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.driver_set_performance_level_CallbackFunctionPointer(domain_id, cookie, performance_level, Mock.driver_set_performance_level_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_driver_set_performance_level(CMOCK_driver_set_performance_level_CALL_INSTANCE* cmock_call_instance, fwk_id_t domain_id, uintptr_t cookie, uint32_t performance_level);
void CMockExpectParameters_driver_set_performance_level(CMOCK_driver_set_performance_level_CALL_INSTANCE* cmock_call_instance, fwk_id_t domain_id, uintptr_t cookie, uint32_t performance_level)
{
  memcpy((void*)(&cmock_call_instance->Expected_domain_id), (void*)(&domain_id),
         sizeof(fwk_id_t[sizeof(domain_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_domain_id = 0;
  memcpy((void*)(&cmock_call_instance->Expected_cookie), (void*)(&cookie),
         sizeof(uintptr_t[sizeof(cookie) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_cookie = 0;
  cmock_call_instance->Expected_performance_level = performance_level;
  cmock_call_instance->IgnoreArg_performance_level = 0;
}

void driver_set_performance_level_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_driver_set_performance_level_CALL_INSTANCE));
  CMOCK_driver_set_performance_level_CALL_INSTANCE* cmock_call_instance = (CMOCK_driver_set_performance_level_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.driver_set_performance_level_CallInstance = CMock_Guts_MemChain(Mock.driver_set_performance_level_CallInstance, cmock_guts_index);
  Mock.driver_set_performance_level_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.driver_set_performance_level_IgnoreBool = (char)1;
}

void driver_set_performance_level_CMockStopIgnore(void)
{
  if(Mock.driver_set_performance_level_IgnoreBool)
    Mock.driver_set_performance_level_CallInstance = CMock_Guts_MemNext(Mock.driver_set_performance_level_CallInstance);
  Mock.driver_set_performance_level_IgnoreBool = (char)0;
}

void driver_set_performance_level_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_driver_set_performance_level_CALL_INSTANCE));
  CMOCK_driver_set_performance_level_CALL_INSTANCE* cmock_call_instance = (CMOCK_driver_set_performance_level_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.driver_set_performance_level_CallInstance = CMock_Guts_MemChain(Mock.driver_set_performance_level_CallInstance, cmock_guts_index);
  Mock.driver_set_performance_level_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void driver_set_performance_level_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t domain_id, uintptr_t cookie, uint32_t performance_level, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_driver_set_performance_level_CALL_INSTANCE));
  CMOCK_driver_set_performance_level_CALL_INSTANCE* cmock_call_instance = (CMOCK_driver_set_performance_level_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.driver_set_performance_level_CallInstance = CMock_Guts_MemChain(Mock.driver_set_performance_level_CallInstance, cmock_guts_index);
  Mock.driver_set_performance_level_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_driver_set_performance_level(cmock_call_instance, domain_id, cookie, performance_level);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void driver_set_performance_level_AddCallback(CMOCK_driver_set_performance_level_CALLBACK Callback)
{
  Mock.driver_set_performance_level_IgnoreBool = (char)0;
  Mock.driver_set_performance_level_CallbackBool = (char)1;
  Mock.driver_set_performance_level_CallbackFunctionPointer = Callback;
}

void driver_set_performance_level_Stub(CMOCK_driver_set_performance_level_CALLBACK Callback)
{
  Mock.driver_set_performance_level_IgnoreBool = (char)0;
  Mock.driver_set_performance_level_CallbackBool = (char)0;
  Mock.driver_set_performance_level_CallbackFunctionPointer = Callback;
}

void driver_set_performance_level_CMockIgnoreArg_domain_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_driver_set_performance_level_CALL_INSTANCE* cmock_call_instance = (CMOCK_driver_set_performance_level_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.driver_set_performance_level_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_domain_id = 1;
}

void driver_set_performance_level_CMockIgnoreArg_cookie(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_driver_set_performance_level_CALL_INSTANCE* cmock_call_instance = (CMOCK_driver_set_performance_level_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.driver_set_performance_level_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cookie = 1;
}

void driver_set_performance_level_CMockIgnoreArg_performance_level(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_driver_set_performance_level_CALL_INSTANCE* cmock_call_instance = (CMOCK_driver_set_performance_level_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.driver_set_performance_level_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_performance_level = 1;
}

int domain_apply_performance_granted_stub(struct mod_perf_controller_domain_ctx* domain_ctx)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_domain_apply_performance_granted_stub);
  cmock_call_instance = (CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.domain_apply_performance_granted_stub_CallInstance);
  Mock.domain_apply_performance_granted_stub_CallInstance = CMock_Guts_MemNext(Mock.domain_apply_performance_granted_stub_CallInstance);
  if (Mock.domain_apply_performance_granted_stub_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.domain_apply_performance_granted_stub_FinalReturn;
    Mock.domain_apply_performance_granted_stub_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.domain_apply_performance_granted_stub_CallbackBool &&
      Mock.domain_apply_performance_granted_stub_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.domain_apply_performance_granted_stub_CallbackFunctionPointer(domain_ctx, Mock.domain_apply_performance_granted_stub_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_domain_ctx)
  {
    UNITY_SET_DETAILS(CMockString_domain_apply_performance_granted_stub,CMockString_domain_ctx);
    if (cmock_call_instance->Expected_domain_ctx == NULL)
      { UNITY_TEST_ASSERT_NULL(domain_ctx, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_domain_ctx), (void*)(domain_ctx), sizeof(struct mod_perf_controller_domain_ctx), cmock_call_instance->Expected_domain_ctx_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.domain_apply_performance_granted_stub_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.domain_apply_performance_granted_stub_CallbackFunctionPointer(domain_ctx, Mock.domain_apply_performance_granted_stub_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_domain_ctx_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(domain_ctx, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)domain_ctx, (void*)cmock_call_instance->ReturnThruPtr_domain_ctx_Val,
      cmock_call_instance->ReturnThruPtr_domain_ctx_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_domain_apply_performance_granted_stub(CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE* cmock_call_instance, struct mod_perf_controller_domain_ctx* domain_ctx, int domain_ctx_Depth);
void CMockExpectParameters_domain_apply_performance_granted_stub(CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE* cmock_call_instance, struct mod_perf_controller_domain_ctx* domain_ctx, int domain_ctx_Depth)
{
  cmock_call_instance->Expected_domain_ctx = domain_ctx;
  cmock_call_instance->Expected_domain_ctx_Depth = domain_ctx_Depth;
  cmock_call_instance->IgnoreArg_domain_ctx = 0;
  cmock_call_instance->ReturnThruPtr_domain_ctx_Used = 0;
}

void domain_apply_performance_granted_stub_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE));
  CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.domain_apply_performance_granted_stub_CallInstance = CMock_Guts_MemChain(Mock.domain_apply_performance_granted_stub_CallInstance, cmock_guts_index);
  Mock.domain_apply_performance_granted_stub_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.domain_apply_performance_granted_stub_IgnoreBool = (char)1;
}

void domain_apply_performance_granted_stub_CMockStopIgnore(void)
{
  if(Mock.domain_apply_performance_granted_stub_IgnoreBool)
    Mock.domain_apply_performance_granted_stub_CallInstance = CMock_Guts_MemNext(Mock.domain_apply_performance_granted_stub_CallInstance);
  Mock.domain_apply_performance_granted_stub_IgnoreBool = (char)0;
}

void domain_apply_performance_granted_stub_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE));
  CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.domain_apply_performance_granted_stub_CallInstance = CMock_Guts_MemChain(Mock.domain_apply_performance_granted_stub_CallInstance, cmock_guts_index);
  Mock.domain_apply_performance_granted_stub_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void domain_apply_performance_granted_stub_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_perf_controller_domain_ctx* domain_ctx, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE));
  CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.domain_apply_performance_granted_stub_CallInstance = CMock_Guts_MemChain(Mock.domain_apply_performance_granted_stub_CallInstance, cmock_guts_index);
  Mock.domain_apply_performance_granted_stub_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_domain_apply_performance_granted_stub(cmock_call_instance, domain_ctx, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void domain_apply_performance_granted_stub_AddCallback(CMOCK_domain_apply_performance_granted_stub_CALLBACK Callback)
{
  Mock.domain_apply_performance_granted_stub_IgnoreBool = (char)0;
  Mock.domain_apply_performance_granted_stub_CallbackBool = (char)1;
  Mock.domain_apply_performance_granted_stub_CallbackFunctionPointer = Callback;
}

void domain_apply_performance_granted_stub_Stub(CMOCK_domain_apply_performance_granted_stub_CALLBACK Callback)
{
  Mock.domain_apply_performance_granted_stub_IgnoreBool = (char)0;
  Mock.domain_apply_performance_granted_stub_CallbackBool = (char)0;
  Mock.domain_apply_performance_granted_stub_CallbackFunctionPointer = Callback;
}

void domain_apply_performance_granted_stub_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, struct mod_perf_controller_domain_ctx* domain_ctx, int domain_ctx_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE));
  CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.domain_apply_performance_granted_stub_CallInstance = CMock_Guts_MemChain(Mock.domain_apply_performance_granted_stub_CallInstance, cmock_guts_index);
  Mock.domain_apply_performance_granted_stub_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_domain_apply_performance_granted_stub(cmock_call_instance, domain_ctx, domain_ctx_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void domain_apply_performance_granted_stub_CMockReturnMemThruPtr_domain_ctx(UNITY_LINE_TYPE cmock_line, struct mod_perf_controller_domain_ctx* domain_ctx, size_t cmock_size)
{
  CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.domain_apply_performance_granted_stub_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_domain_ctx_Used = 1;
  cmock_call_instance->ReturnThruPtr_domain_ctx_Val = domain_ctx;
  cmock_call_instance->ReturnThruPtr_domain_ctx_Size = cmock_size;
}

void domain_apply_performance_granted_stub_CMockIgnoreArg_domain_ctx(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_domain_apply_performance_granted_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.domain_apply_performance_granted_stub_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_domain_ctx = 1;
}

