/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_scmi_extra.h"

static const char* CMockString_channel_id = "channel_id";
static const char* CMockString_command_count = "command_count";
static const char* CMockString_get_max_payload_size = "get_max_payload_size";
static const char* CMockString_handler_table = "handler_table";
static const char* CMockString_message_id = "message_id";
static const char* CMockString_mod_scmi_from_protocol_api_scmi_frame_validation = "mod_scmi_from_protocol_api_scmi_frame_validation";
static const char* CMockString_offset = "offset";
static const char* CMockString_payload = "payload";
static const char* CMockString_payload_size = "payload_size";
static const char* CMockString_payload_size_table = "payload_size_table";
static const char* CMockString_protocol_id = "protocol_id";
static const char* CMockString_respond = "respond";
static const char* CMockString_scmi_write_payload = "scmi_write_payload";
static const char* CMockString_service_id = "service_id";
static const char* CMockString_size = "size";

typedef struct _CMOCK_respond_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_service_id;
  const void* Expected_payload;
  size_t Expected_size;
  int Expected_payload_Depth;
  char IgnoreArg_service_id;
  char IgnoreArg_payload;
  char IgnoreArg_size;

} CMOCK_respond_CALL_INSTANCE;

typedef struct _CMOCK_scmi_write_payload_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_channel_id;
  size_t Expected_offset;
  const void* Expected_payload;
  size_t Expected_size;
  int Expected_payload_Depth;
  char IgnoreArg_channel_id;
  char IgnoreArg_offset;
  char IgnoreArg_payload;
  char IgnoreArg_size;

} CMOCK_scmi_write_payload_CALL_INSTANCE;

typedef struct _CMOCK_get_max_payload_size_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_service_id;
  size_t* Expected_size;
  int Expected_size_Depth;
  char ReturnThruPtr_size_Used;
  size_t* ReturnThruPtr_size_Val;
  size_t ReturnThruPtr_size_Size;
  char IgnoreArg_service_id;
  char IgnoreArg_size;

} CMOCK_get_max_payload_size_CALL_INSTANCE;

typedef struct _CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  uint8_t Expected_protocol_id;
  fwk_id_t Expected_service_id;
  const uint32_t* Expected_payload;
  size_t Expected_payload_size;
  size_t Expected_message_id;
  const size_t* Expected_payload_size_table;
  size_t Expected_command_count;
  const handler_table_t* Expected_handler_table;
  int Expected_payload_Depth;
  int Expected_payload_size_table_Depth;
  int Expected_handler_table_Depth;
  char IgnoreArg_protocol_id;
  char IgnoreArg_service_id;
  char IgnoreArg_payload;
  char IgnoreArg_payload_size;
  char IgnoreArg_message_id;
  char IgnoreArg_payload_size_table;
  char IgnoreArg_command_count;
  char IgnoreArg_handler_table;

} CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE;

static struct Mockmod_scmi_extraInstance
{
  char respond_IgnoreBool;
  int respond_FinalReturn;
  char respond_CallbackBool;
  CMOCK_respond_CALLBACK respond_CallbackFunctionPointer;
  int respond_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE respond_CallInstance;
  char scmi_write_payload_IgnoreBool;
  int scmi_write_payload_FinalReturn;
  char scmi_write_payload_CallbackBool;
  CMOCK_scmi_write_payload_CALLBACK scmi_write_payload_CallbackFunctionPointer;
  int scmi_write_payload_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE scmi_write_payload_CallInstance;
  char get_max_payload_size_IgnoreBool;
  int get_max_payload_size_FinalReturn;
  char get_max_payload_size_CallbackBool;
  CMOCK_get_max_payload_size_CALLBACK get_max_payload_size_CallbackFunctionPointer;
  int get_max_payload_size_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_max_payload_size_CallInstance;
  char mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool;
  int mod_scmi_from_protocol_api_scmi_frame_validation_FinalReturn;
  char mod_scmi_from_protocol_api_scmi_frame_validation_CallbackBool;
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALLBACK mod_scmi_from_protocol_api_scmi_frame_validation_CallbackFunctionPointer;
  int mod_scmi_from_protocol_api_scmi_frame_validation_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_scmi_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.respond_CallInstance;
  if (Mock.respond_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_respond);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.respond_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.scmi_write_payload_CallInstance;
  if (Mock.scmi_write_payload_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_scmi_write_payload);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.scmi_write_payload_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.get_max_payload_size_CallInstance;
  if (Mock.get_max_payload_size_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_max_payload_size);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_max_payload_size_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance;
  if (Mock.mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mod_scmi_from_protocol_api_scmi_frame_validation);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_scmi_extra_Init(void)
{
  Mockmod_scmi_extra_Destroy();
}

void Mockmod_scmi_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int respond(fwk_id_t service_id, const void* payload, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_respond_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_respond);
  cmock_call_instance = (CMOCK_respond_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.respond_CallInstance);
  Mock.respond_CallInstance = CMock_Guts_MemNext(Mock.respond_CallInstance);
  if (Mock.respond_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.respond_FinalReturn;
    Mock.respond_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.respond_CallbackBool &&
      Mock.respond_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.respond_CallbackFunctionPointer(service_id, payload, size, Mock.respond_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_service_id)
  {
    UNITY_SET_DETAILS(CMockString_respond,CMockString_service_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_payload)
  {
    UNITY_SET_DETAILS(CMockString_respond,CMockString_payload);
    if (cmock_call_instance->Expected_payload == NULL)
      { UNITY_TEST_ASSERT_NULL(payload, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_payload, payload, cmock_call_instance->Expected_payload_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_size)
  {
    UNITY_SET_DETAILS(CMockString_respond,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.respond_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.respond_CallbackFunctionPointer(service_id, payload, size, Mock.respond_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_respond(CMOCK_respond_CALL_INSTANCE* cmock_call_instance, fwk_id_t service_id, const void* payload, int payload_Depth, size_t size);
void CMockExpectParameters_respond(CMOCK_respond_CALL_INSTANCE* cmock_call_instance, fwk_id_t service_id, const void* payload, int payload_Depth, size_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id),
         sizeof(fwk_id_t[sizeof(service_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_service_id = 0;
  cmock_call_instance->Expected_payload = payload;
  cmock_call_instance->Expected_payload_Depth = payload_Depth;
  cmock_call_instance->IgnoreArg_payload = 0;
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_size = 0;
}

void respond_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_respond_CALL_INSTANCE));
  CMOCK_respond_CALL_INSTANCE* cmock_call_instance = (CMOCK_respond_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.respond_CallInstance = CMock_Guts_MemChain(Mock.respond_CallInstance, cmock_guts_index);
  Mock.respond_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.respond_IgnoreBool = (char)1;
}

void respond_CMockStopIgnore(void)
{
  if(Mock.respond_IgnoreBool)
    Mock.respond_CallInstance = CMock_Guts_MemNext(Mock.respond_CallInstance);
  Mock.respond_IgnoreBool = (char)0;
}

void respond_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_respond_CALL_INSTANCE));
  CMOCK_respond_CALL_INSTANCE* cmock_call_instance = (CMOCK_respond_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.respond_CallInstance = CMock_Guts_MemChain(Mock.respond_CallInstance, cmock_guts_index);
  Mock.respond_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void respond_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, const void* payload, size_t size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_respond_CALL_INSTANCE));
  CMOCK_respond_CALL_INSTANCE* cmock_call_instance = (CMOCK_respond_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.respond_CallInstance = CMock_Guts_MemChain(Mock.respond_CallInstance, cmock_guts_index);
  Mock.respond_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_respond(cmock_call_instance, service_id, payload, size, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void respond_AddCallback(CMOCK_respond_CALLBACK Callback)
{
  Mock.respond_IgnoreBool = (char)0;
  Mock.respond_CallbackBool = (char)1;
  Mock.respond_CallbackFunctionPointer = Callback;
}

void respond_Stub(CMOCK_respond_CALLBACK Callback)
{
  Mock.respond_IgnoreBool = (char)0;
  Mock.respond_CallbackBool = (char)0;
  Mock.respond_CallbackFunctionPointer = Callback;
}

void respond_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, const void* payload, int payload_Depth, size_t size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_respond_CALL_INSTANCE));
  CMOCK_respond_CALL_INSTANCE* cmock_call_instance = (CMOCK_respond_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.respond_CallInstance = CMock_Guts_MemChain(Mock.respond_CallInstance, cmock_guts_index);
  Mock.respond_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_respond(cmock_call_instance, service_id, payload, payload_Depth, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void respond_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_respond_CALL_INSTANCE* cmock_call_instance = (CMOCK_respond_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.respond_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_service_id = 1;
}

void respond_CMockIgnoreArg_payload(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_respond_CALL_INSTANCE* cmock_call_instance = (CMOCK_respond_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.respond_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_payload = 1;
}

void respond_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_respond_CALL_INSTANCE* cmock_call_instance = (CMOCK_respond_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.respond_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_size = 1;
}

int scmi_write_payload(fwk_id_t channel_id, size_t offset, const void* payload, size_t size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_scmi_write_payload_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_scmi_write_payload);
  cmock_call_instance = (CMOCK_scmi_write_payload_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.scmi_write_payload_CallInstance);
  Mock.scmi_write_payload_CallInstance = CMock_Guts_MemNext(Mock.scmi_write_payload_CallInstance);
  if (Mock.scmi_write_payload_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.scmi_write_payload_FinalReturn;
    Mock.scmi_write_payload_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.scmi_write_payload_CallbackBool &&
      Mock.scmi_write_payload_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.scmi_write_payload_CallbackFunctionPointer(channel_id, offset, payload, size, Mock.scmi_write_payload_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_channel_id)
  {
    UNITY_SET_DETAILS(CMockString_scmi_write_payload,CMockString_channel_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_channel_id), (void*)(&channel_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_offset)
  {
    UNITY_SET_DETAILS(CMockString_scmi_write_payload,CMockString_offset);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_offset), (void*)(&offset), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_payload)
  {
    UNITY_SET_DETAILS(CMockString_scmi_write_payload,CMockString_payload);
    if (cmock_call_instance->Expected_payload == NULL)
      { UNITY_TEST_ASSERT_NULL(payload, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_payload, payload, cmock_call_instance->Expected_payload_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_size)
  {
    UNITY_SET_DETAILS(CMockString_scmi_write_payload,CMockString_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_size), (void*)(&size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.scmi_write_payload_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.scmi_write_payload_CallbackFunctionPointer(channel_id, offset, payload, size, Mock.scmi_write_payload_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_scmi_write_payload(CMOCK_scmi_write_payload_CALL_INSTANCE* cmock_call_instance, fwk_id_t channel_id, size_t offset, const void* payload, int payload_Depth, size_t size);
void CMockExpectParameters_scmi_write_payload(CMOCK_scmi_write_payload_CALL_INSTANCE* cmock_call_instance, fwk_id_t channel_id, size_t offset, const void* payload, int payload_Depth, size_t size)
{
  memcpy((void*)(&cmock_call_instance->Expected_channel_id), (void*)(&channel_id),
         sizeof(fwk_id_t[sizeof(channel_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_channel_id = 0;
  memcpy((void*)(&cmock_call_instance->Expected_offset), (void*)(&offset),
         sizeof(size_t[sizeof(offset) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_offset = 0;
  cmock_call_instance->Expected_payload = payload;
  cmock_call_instance->Expected_payload_Depth = payload_Depth;
  cmock_call_instance->IgnoreArg_payload = 0;
  memcpy((void*)(&cmock_call_instance->Expected_size), (void*)(&size),
         sizeof(size_t[sizeof(size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_size = 0;
}

void scmi_write_payload_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_scmi_write_payload_CALL_INSTANCE));
  CMOCK_scmi_write_payload_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_write_payload_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.scmi_write_payload_CallInstance = CMock_Guts_MemChain(Mock.scmi_write_payload_CallInstance, cmock_guts_index);
  Mock.scmi_write_payload_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.scmi_write_payload_IgnoreBool = (char)1;
}

void scmi_write_payload_CMockStopIgnore(void)
{
  if(Mock.scmi_write_payload_IgnoreBool)
    Mock.scmi_write_payload_CallInstance = CMock_Guts_MemNext(Mock.scmi_write_payload_CallInstance);
  Mock.scmi_write_payload_IgnoreBool = (char)0;
}

void scmi_write_payload_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_scmi_write_payload_CALL_INSTANCE));
  CMOCK_scmi_write_payload_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_write_payload_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.scmi_write_payload_CallInstance = CMock_Guts_MemChain(Mock.scmi_write_payload_CallInstance, cmock_guts_index);
  Mock.scmi_write_payload_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void scmi_write_payload_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t channel_id, size_t offset, const void* payload, size_t size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_scmi_write_payload_CALL_INSTANCE));
  CMOCK_scmi_write_payload_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_write_payload_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.scmi_write_payload_CallInstance = CMock_Guts_MemChain(Mock.scmi_write_payload_CallInstance, cmock_guts_index);
  Mock.scmi_write_payload_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_scmi_write_payload(cmock_call_instance, channel_id, offset, payload, size, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void scmi_write_payload_AddCallback(CMOCK_scmi_write_payload_CALLBACK Callback)
{
  Mock.scmi_write_payload_IgnoreBool = (char)0;
  Mock.scmi_write_payload_CallbackBool = (char)1;
  Mock.scmi_write_payload_CallbackFunctionPointer = Callback;
}

void scmi_write_payload_Stub(CMOCK_scmi_write_payload_CALLBACK Callback)
{
  Mock.scmi_write_payload_IgnoreBool = (char)0;
  Mock.scmi_write_payload_CallbackBool = (char)0;
  Mock.scmi_write_payload_CallbackFunctionPointer = Callback;
}

void scmi_write_payload_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t channel_id, size_t offset, const void* payload, int payload_Depth, size_t size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_scmi_write_payload_CALL_INSTANCE));
  CMOCK_scmi_write_payload_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_write_payload_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.scmi_write_payload_CallInstance = CMock_Guts_MemChain(Mock.scmi_write_payload_CallInstance, cmock_guts_index);
  Mock.scmi_write_payload_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_scmi_write_payload(cmock_call_instance, channel_id, offset, payload, payload_Depth, size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void scmi_write_payload_CMockIgnoreArg_channel_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_scmi_write_payload_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_write_payload_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.scmi_write_payload_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_channel_id = 1;
}

void scmi_write_payload_CMockIgnoreArg_offset(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_scmi_write_payload_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_write_payload_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.scmi_write_payload_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_offset = 1;
}

void scmi_write_payload_CMockIgnoreArg_payload(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_scmi_write_payload_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_write_payload_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.scmi_write_payload_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_payload = 1;
}

void scmi_write_payload_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_scmi_write_payload_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_write_payload_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.scmi_write_payload_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_size = 1;
}

int get_max_payload_size(fwk_id_t service_id, size_t* size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_max_payload_size_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_max_payload_size);
  cmock_call_instance = (CMOCK_get_max_payload_size_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_max_payload_size_CallInstance);
  Mock.get_max_payload_size_CallInstance = CMock_Guts_MemNext(Mock.get_max_payload_size_CallInstance);
  if (Mock.get_max_payload_size_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_max_payload_size_FinalReturn;
    Mock.get_max_payload_size_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_max_payload_size_CallbackBool &&
      Mock.get_max_payload_size_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.get_max_payload_size_CallbackFunctionPointer(service_id, size, Mock.get_max_payload_size_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_service_id)
  {
    UNITY_SET_DETAILS(CMockString_get_max_payload_size,CMockString_service_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_size)
  {
    UNITY_SET_DETAILS(CMockString_get_max_payload_size,CMockString_size);
    if (cmock_call_instance->Expected_size == NULL)
      { UNITY_TEST_ASSERT_NULL(size, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_size), (void*)(size), sizeof(size_t), cmock_call_instance->Expected_size_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.get_max_payload_size_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_max_payload_size_CallbackFunctionPointer(service_id, size, Mock.get_max_payload_size_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_size_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(size, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)size, (void*)cmock_call_instance->ReturnThruPtr_size_Val,
      cmock_call_instance->ReturnThruPtr_size_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_max_payload_size(CMOCK_get_max_payload_size_CALL_INSTANCE* cmock_call_instance, fwk_id_t service_id, size_t* size, int size_Depth);
void CMockExpectParameters_get_max_payload_size(CMOCK_get_max_payload_size_CALL_INSTANCE* cmock_call_instance, fwk_id_t service_id, size_t* size, int size_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id),
         sizeof(fwk_id_t[sizeof(service_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_service_id = 0;
  cmock_call_instance->Expected_size = size;
  cmock_call_instance->Expected_size_Depth = size_Depth;
  cmock_call_instance->IgnoreArg_size = 0;
  cmock_call_instance->ReturnThruPtr_size_Used = 0;
}

void get_max_payload_size_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_max_payload_size_CALL_INSTANCE));
  CMOCK_get_max_payload_size_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_max_payload_size_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_max_payload_size_CallInstance = CMock_Guts_MemChain(Mock.get_max_payload_size_CallInstance, cmock_guts_index);
  Mock.get_max_payload_size_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_max_payload_size_IgnoreBool = (char)1;
}

void get_max_payload_size_CMockStopIgnore(void)
{
  if(Mock.get_max_payload_size_IgnoreBool)
    Mock.get_max_payload_size_CallInstance = CMock_Guts_MemNext(Mock.get_max_payload_size_CallInstance);
  Mock.get_max_payload_size_IgnoreBool = (char)0;
}

void get_max_payload_size_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_max_payload_size_CALL_INSTANCE));
  CMOCK_get_max_payload_size_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_max_payload_size_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_max_payload_size_CallInstance = CMock_Guts_MemChain(Mock.get_max_payload_size_CallInstance, cmock_guts_index);
  Mock.get_max_payload_size_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_max_payload_size_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, size_t* size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_max_payload_size_CALL_INSTANCE));
  CMOCK_get_max_payload_size_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_max_payload_size_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_max_payload_size_CallInstance = CMock_Guts_MemChain(Mock.get_max_payload_size_CallInstance, cmock_guts_index);
  Mock.get_max_payload_size_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_max_payload_size(cmock_call_instance, service_id, size, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_max_payload_size_AddCallback(CMOCK_get_max_payload_size_CALLBACK Callback)
{
  Mock.get_max_payload_size_IgnoreBool = (char)0;
  Mock.get_max_payload_size_CallbackBool = (char)1;
  Mock.get_max_payload_size_CallbackFunctionPointer = Callback;
}

void get_max_payload_size_Stub(CMOCK_get_max_payload_size_CALLBACK Callback)
{
  Mock.get_max_payload_size_IgnoreBool = (char)0;
  Mock.get_max_payload_size_CallbackBool = (char)0;
  Mock.get_max_payload_size_CallbackFunctionPointer = Callback;
}

void get_max_payload_size_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, size_t* size, int size_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_max_payload_size_CALL_INSTANCE));
  CMOCK_get_max_payload_size_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_max_payload_size_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_max_payload_size_CallInstance = CMock_Guts_MemChain(Mock.get_max_payload_size_CallInstance, cmock_guts_index);
  Mock.get_max_payload_size_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_max_payload_size(cmock_call_instance, service_id, size, size_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_max_payload_size_CMockReturnMemThruPtr_size(UNITY_LINE_TYPE cmock_line, size_t* size, size_t cmock_size)
{
  CMOCK_get_max_payload_size_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_max_payload_size_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_max_payload_size_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_size_Used = 1;
  cmock_call_instance->ReturnThruPtr_size_Val = size;
  cmock_call_instance->ReturnThruPtr_size_Size = cmock_size;
}

void get_max_payload_size_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_max_payload_size_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_max_payload_size_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_max_payload_size_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_service_id = 1;
}

void get_max_payload_size_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_max_payload_size_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_max_payload_size_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_max_payload_size_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_size = 1;
}

int mod_scmi_from_protocol_api_scmi_frame_validation(uint8_t protocol_id, fwk_id_t service_id, const uint32_t* payload, size_t payload_size, size_t message_id, const size_t* payload_size_table, size_t command_count, const handler_table_t* handler_table)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mod_scmi_from_protocol_api_scmi_frame_validation);
  cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance);
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance = CMock_Guts_MemNext(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance);
  if (Mock.mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.mod_scmi_from_protocol_api_scmi_frame_validation_FinalReturn;
    Mock.mod_scmi_from_protocol_api_scmi_frame_validation_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackBool &&
      Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackFunctionPointer(protocol_id, service_id, payload, payload_size, message_id, payload_size_table, command_count, handler_table, Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_protocol_id)
  {
    UNITY_SET_DETAILS(CMockString_mod_scmi_from_protocol_api_scmi_frame_validation,CMockString_protocol_id);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_protocol_id, protocol_id, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_service_id)
  {
    UNITY_SET_DETAILS(CMockString_mod_scmi_from_protocol_api_scmi_frame_validation,CMockString_service_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_payload)
  {
    UNITY_SET_DETAILS(CMockString_mod_scmi_from_protocol_api_scmi_frame_validation,CMockString_payload);
    if (cmock_call_instance->Expected_payload == NULL)
      { UNITY_TEST_ASSERT_NULL(payload, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_payload, payload, cmock_call_instance->Expected_payload_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_payload_size)
  {
    UNITY_SET_DETAILS(CMockString_mod_scmi_from_protocol_api_scmi_frame_validation,CMockString_payload_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_payload_size), (void*)(&payload_size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_message_id)
  {
    UNITY_SET_DETAILS(CMockString_mod_scmi_from_protocol_api_scmi_frame_validation,CMockString_message_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_message_id), (void*)(&message_id), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_payload_size_table)
  {
    UNITY_SET_DETAILS(CMockString_mod_scmi_from_protocol_api_scmi_frame_validation,CMockString_payload_size_table);
    if (cmock_call_instance->Expected_payload_size_table == NULL)
      { UNITY_TEST_ASSERT_NULL(payload_size_table, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_payload_size_table), (void*)(payload_size_table), sizeof(const size_t), cmock_call_instance->Expected_payload_size_table_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_command_count)
  {
    UNITY_SET_DETAILS(CMockString_mod_scmi_from_protocol_api_scmi_frame_validation,CMockString_command_count);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_command_count), (void*)(&command_count), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_handler_table)
  {
    UNITY_SET_DETAILS(CMockString_mod_scmi_from_protocol_api_scmi_frame_validation,CMockString_handler_table);
    if (cmock_call_instance->Expected_handler_table == NULL)
      { UNITY_TEST_ASSERT_NULL(handler_table, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_handler_table), (void*)(handler_table), sizeof(const handler_table_t), cmock_call_instance->Expected_handler_table_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackFunctionPointer(protocol_id, service_id, payload, payload_size, message_id, payload_size_table, command_count, handler_table, Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mod_scmi_from_protocol_api_scmi_frame_validation(CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance, uint8_t protocol_id, fwk_id_t service_id, const uint32_t* payload, int payload_Depth, size_t payload_size, size_t message_id, const size_t* payload_size_table, int payload_size_table_Depth, size_t command_count, const handler_table_t* handler_table, int handler_table_Depth);
void CMockExpectParameters_mod_scmi_from_protocol_api_scmi_frame_validation(CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance, uint8_t protocol_id, fwk_id_t service_id, const uint32_t* payload, int payload_Depth, size_t payload_size, size_t message_id, const size_t* payload_size_table, int payload_size_table_Depth, size_t command_count, const handler_table_t* handler_table, int handler_table_Depth)
{
  cmock_call_instance->Expected_protocol_id = protocol_id;
  cmock_call_instance->IgnoreArg_protocol_id = 0;
  memcpy((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id),
         sizeof(fwk_id_t[sizeof(service_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_service_id = 0;
  cmock_call_instance->Expected_payload = payload;
  cmock_call_instance->Expected_payload_Depth = payload_Depth;
  cmock_call_instance->IgnoreArg_payload = 0;
  memcpy((void*)(&cmock_call_instance->Expected_payload_size), (void*)(&payload_size),
         sizeof(size_t[sizeof(payload_size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_payload_size = 0;
  memcpy((void*)(&cmock_call_instance->Expected_message_id), (void*)(&message_id),
         sizeof(size_t[sizeof(message_id) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_message_id = 0;
  cmock_call_instance->Expected_payload_size_table = payload_size_table;
  cmock_call_instance->Expected_payload_size_table_Depth = payload_size_table_Depth;
  cmock_call_instance->IgnoreArg_payload_size_table = 0;
  memcpy((void*)(&cmock_call_instance->Expected_command_count), (void*)(&command_count),
         sizeof(size_t[sizeof(command_count) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_command_count = 0;
  cmock_call_instance->Expected_handler_table = handler_table;
  cmock_call_instance->Expected_handler_table_Depth = handler_table_Depth;
  cmock_call_instance->IgnoreArg_handler_table = 0;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE));
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance = CMock_Guts_MemChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance, cmock_guts_index);
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool = (char)1;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockStopIgnore(void)
{
  if(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool)
    Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance = CMock_Guts_MemNext(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance);
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool = (char)0;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE));
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance = CMock_Guts_MemChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance, cmock_guts_index);
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t protocol_id, fwk_id_t service_id, const uint32_t* payload, size_t payload_size, size_t message_id, const size_t* payload_size_table, size_t command_count, const handler_table_t* handler_table, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE));
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance = CMock_Guts_MemChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance, cmock_guts_index);
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mod_scmi_from_protocol_api_scmi_frame_validation(cmock_call_instance, protocol_id, service_id, payload, payload_size, payload_size, message_id, payload_size_table, 1, command_count, handler_table, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_AddCallback(CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALLBACK Callback)
{
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool = (char)0;
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackBool = (char)1;
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackFunctionPointer = Callback;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_Stub(CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALLBACK Callback)
{
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool = (char)0;
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackBool = (char)0;
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallbackFunctionPointer = Callback;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t protocol_id, fwk_id_t service_id, const uint32_t* payload, int payload_Depth, size_t payload_size, size_t message_id, const size_t* payload_size_table, int payload_size_table_Depth, size_t command_count, const handler_table_t* handler_table, int handler_table_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE));
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance = CMock_Guts_MemChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance, cmock_guts_index);
  Mock.mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mod_scmi_from_protocol_api_scmi_frame_validation(cmock_call_instance, protocol_id, service_id, payload, payload_Depth, payload_size, message_id, payload_size_table, payload_size_table_Depth, command_count, handler_table, handler_table_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_protocol_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_protocol_id = 1;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_service_id = 1;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_payload(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_payload = 1;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_payload_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_payload_size = 1;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_message_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_message_id = 1;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_payload_size_table(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_payload_size_table = 1;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_command_count(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_command_count = 1;
}

void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_handler_table(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_scmi_from_protocol_api_scmi_frame_validation_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_handler_table = 1;
}

