/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMOD_SCMI_EXTRA_H
#define _MOCKMOD_SCMI_EXTRA_H

#include "unity.h"
#include "mod_scmi_extra.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockmod_scmi_extra_Init(void);
void Mockmod_scmi_extra_Destroy(void);
void Mockmod_scmi_extra_Verify(void);




#define respond_IgnoreAndReturn(cmock_retval) respond_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void respond_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define respond_StopIgnore() respond_CMockStopIgnore()
void respond_CMockStopIgnore(void);
#define respond_ExpectAnyArgsAndReturn(cmock_retval) respond_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void respond_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define respond_ExpectAndReturn(service_id, payload, size, cmock_retval) respond_CMockExpectAndReturn(__LINE__, service_id, payload, size, cmock_retval)
void respond_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, const void* payload, size_t size, int cmock_to_return);
typedef int (* CMOCK_respond_CALLBACK)(fwk_id_t service_id, const void* payload, size_t size, int cmock_num_calls);
void respond_AddCallback(CMOCK_respond_CALLBACK Callback);
void respond_Stub(CMOCK_respond_CALLBACK Callback);
#define respond_StubWithCallback respond_Stub
#define respond_ExpectWithArrayAndReturn(service_id, payload, payload_Depth, size, cmock_retval) respond_CMockExpectWithArrayAndReturn(__LINE__, service_id, payload, payload_Depth, size, cmock_retval)
void respond_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, const void* payload, int payload_Depth, size_t size, int cmock_to_return);
#define respond_IgnoreArg_service_id() respond_CMockIgnoreArg_service_id(__LINE__)
void respond_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line);
#define respond_IgnoreArg_payload() respond_CMockIgnoreArg_payload(__LINE__)
void respond_CMockIgnoreArg_payload(UNITY_LINE_TYPE cmock_line);
#define respond_IgnoreArg_size() respond_CMockIgnoreArg_size(__LINE__)
void respond_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line);
#define scmi_write_payload_IgnoreAndReturn(cmock_retval) scmi_write_payload_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void scmi_write_payload_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define scmi_write_payload_StopIgnore() scmi_write_payload_CMockStopIgnore()
void scmi_write_payload_CMockStopIgnore(void);
#define scmi_write_payload_ExpectAnyArgsAndReturn(cmock_retval) scmi_write_payload_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void scmi_write_payload_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define scmi_write_payload_ExpectAndReturn(channel_id, offset, payload, size, cmock_retval) scmi_write_payload_CMockExpectAndReturn(__LINE__, channel_id, offset, payload, size, cmock_retval)
void scmi_write_payload_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t channel_id, size_t offset, const void* payload, size_t size, int cmock_to_return);
typedef int (* CMOCK_scmi_write_payload_CALLBACK)(fwk_id_t channel_id, size_t offset, const void* payload, size_t size, int cmock_num_calls);
void scmi_write_payload_AddCallback(CMOCK_scmi_write_payload_CALLBACK Callback);
void scmi_write_payload_Stub(CMOCK_scmi_write_payload_CALLBACK Callback);
#define scmi_write_payload_StubWithCallback scmi_write_payload_Stub
#define scmi_write_payload_ExpectWithArrayAndReturn(channel_id, offset, payload, payload_Depth, size, cmock_retval) scmi_write_payload_CMockExpectWithArrayAndReturn(__LINE__, channel_id, offset, payload, payload_Depth, size, cmock_retval)
void scmi_write_payload_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t channel_id, size_t offset, const void* payload, int payload_Depth, size_t size, int cmock_to_return);
#define scmi_write_payload_IgnoreArg_channel_id() scmi_write_payload_CMockIgnoreArg_channel_id(__LINE__)
void scmi_write_payload_CMockIgnoreArg_channel_id(UNITY_LINE_TYPE cmock_line);
#define scmi_write_payload_IgnoreArg_offset() scmi_write_payload_CMockIgnoreArg_offset(__LINE__)
void scmi_write_payload_CMockIgnoreArg_offset(UNITY_LINE_TYPE cmock_line);
#define scmi_write_payload_IgnoreArg_payload() scmi_write_payload_CMockIgnoreArg_payload(__LINE__)
void scmi_write_payload_CMockIgnoreArg_payload(UNITY_LINE_TYPE cmock_line);
#define scmi_write_payload_IgnoreArg_size() scmi_write_payload_CMockIgnoreArg_size(__LINE__)
void scmi_write_payload_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line);
#define get_max_payload_size_IgnoreAndReturn(cmock_retval) get_max_payload_size_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_max_payload_size_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_max_payload_size_StopIgnore() get_max_payload_size_CMockStopIgnore()
void get_max_payload_size_CMockStopIgnore(void);
#define get_max_payload_size_ExpectAnyArgsAndReturn(cmock_retval) get_max_payload_size_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void get_max_payload_size_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_max_payload_size_ExpectAndReturn(service_id, size, cmock_retval) get_max_payload_size_CMockExpectAndReturn(__LINE__, service_id, size, cmock_retval)
void get_max_payload_size_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, size_t* size, int cmock_to_return);
typedef int (* CMOCK_get_max_payload_size_CALLBACK)(fwk_id_t service_id, size_t* size, int cmock_num_calls);
void get_max_payload_size_AddCallback(CMOCK_get_max_payload_size_CALLBACK Callback);
void get_max_payload_size_Stub(CMOCK_get_max_payload_size_CALLBACK Callback);
#define get_max_payload_size_StubWithCallback get_max_payload_size_Stub
#define get_max_payload_size_ExpectWithArrayAndReturn(service_id, size, size_Depth, cmock_retval) get_max_payload_size_CMockExpectWithArrayAndReturn(__LINE__, service_id, size, size_Depth, cmock_retval)
void get_max_payload_size_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, size_t* size, int size_Depth, int cmock_to_return);
#define get_max_payload_size_ReturnThruPtr_size(size) get_max_payload_size_CMockReturnMemThruPtr_size(__LINE__, size, sizeof(size_t))
#define get_max_payload_size_ReturnArrayThruPtr_size(size, cmock_len) get_max_payload_size_CMockReturnMemThruPtr_size(__LINE__, size, cmock_len * sizeof(*size))
#define get_max_payload_size_ReturnMemThruPtr_size(size, cmock_size) get_max_payload_size_CMockReturnMemThruPtr_size(__LINE__, size, cmock_size)
void get_max_payload_size_CMockReturnMemThruPtr_size(UNITY_LINE_TYPE cmock_line, size_t* size, size_t cmock_size);
#define get_max_payload_size_IgnoreArg_service_id() get_max_payload_size_CMockIgnoreArg_service_id(__LINE__)
void get_max_payload_size_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line);
#define get_max_payload_size_IgnoreArg_size() get_max_payload_size_CMockIgnoreArg_size(__LINE__)
void get_max_payload_size_CMockIgnoreArg_size(UNITY_LINE_TYPE cmock_line);
#define mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreAndReturn(cmock_retval) mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define mod_scmi_from_protocol_api_scmi_frame_validation_StopIgnore() mod_scmi_from_protocol_api_scmi_frame_validation_CMockStopIgnore()
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockStopIgnore(void);
#define mod_scmi_from_protocol_api_scmi_frame_validation_ExpectAnyArgsAndReturn(cmock_retval) mod_scmi_from_protocol_api_scmi_frame_validation_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define mod_scmi_from_protocol_api_scmi_frame_validation_ExpectAndReturn(protocol_id, service_id, payload, payload_size, message_id, payload_size_table, command_count, handler_table, cmock_retval) mod_scmi_from_protocol_api_scmi_frame_validation_CMockExpectAndReturn(__LINE__, protocol_id, service_id, payload, payload_size, message_id, payload_size_table, command_count, handler_table, cmock_retval)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t protocol_id, fwk_id_t service_id, const uint32_t* payload, size_t payload_size, size_t message_id, const size_t* payload_size_table, size_t command_count, const handler_table_t* handler_table, int cmock_to_return);
typedef int (* CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALLBACK)(uint8_t protocol_id, fwk_id_t service_id, const uint32_t* payload, size_t payload_size, size_t message_id, const size_t* payload_size_table, size_t command_count, const handler_table_t* handler_table, int cmock_num_calls);
void mod_scmi_from_protocol_api_scmi_frame_validation_AddCallback(CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALLBACK Callback);
void mod_scmi_from_protocol_api_scmi_frame_validation_Stub(CMOCK_mod_scmi_from_protocol_api_scmi_frame_validation_CALLBACK Callback);
#define mod_scmi_from_protocol_api_scmi_frame_validation_StubWithCallback mod_scmi_from_protocol_api_scmi_frame_validation_Stub
#define mod_scmi_from_protocol_api_scmi_frame_validation_ExpectWithArrayAndReturn(protocol_id, service_id, payload, payload_Depth, payload_size, message_id, payload_size_table, payload_size_table_Depth, command_count, handler_table, handler_table_Depth, cmock_retval) mod_scmi_from_protocol_api_scmi_frame_validation_CMockExpectWithArrayAndReturn(__LINE__, protocol_id, service_id, payload, payload_Depth, payload_size, message_id, payload_size_table, payload_size_table_Depth, command_count, handler_table, handler_table_Depth, cmock_retval)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t protocol_id, fwk_id_t service_id, const uint32_t* payload, int payload_Depth, size_t payload_size, size_t message_id, const size_t* payload_size_table, int payload_size_table_Depth, size_t command_count, const handler_table_t* handler_table, int handler_table_Depth, int cmock_to_return);
#define mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreArg_protocol_id() mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_protocol_id(__LINE__)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_protocol_id(UNITY_LINE_TYPE cmock_line);
#define mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreArg_service_id() mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_service_id(__LINE__)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line);
#define mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreArg_payload() mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_payload(__LINE__)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_payload(UNITY_LINE_TYPE cmock_line);
#define mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreArg_payload_size() mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_payload_size(__LINE__)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_payload_size(UNITY_LINE_TYPE cmock_line);
#define mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreArg_message_id() mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_message_id(__LINE__)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_message_id(UNITY_LINE_TYPE cmock_line);
#define mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreArg_payload_size_table() mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_payload_size_table(__LINE__)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_payload_size_table(UNITY_LINE_TYPE cmock_line);
#define mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreArg_command_count() mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_command_count(__LINE__)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_command_count(UNITY_LINE_TYPE cmock_line);
#define mod_scmi_from_protocol_api_scmi_frame_validation_IgnoreArg_handler_table() mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_handler_table(__LINE__)
void mod_scmi_from_protocol_api_scmi_frame_validation_CMockIgnoreArg_handler_table(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
