/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_thermal_power_estimator_extra.h"

static const char* CMockString_data = "data";
static const char* CMockString_id = "id";
static const char* CMockString_input = "input";
static const char* CMockString_mod_pid_controller_update = "mod_pid_controller_update";
static const char* CMockString_mod_sensor_get_data = "mod_sensor_get_data";
static const char* CMockString_output = "output";

typedef struct _CMOCK_mod_pid_controller_update_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  int64_t Expected_input;
  int64_t* Expected_output;
  int Expected_output_Depth;
  char ReturnThruPtr_output_Used;
  int64_t* ReturnThruPtr_output_Val;
  size_t ReturnThruPtr_output_Size;
  char IgnoreArg_id;
  char IgnoreArg_input;
  char IgnoreArg_output;

} CMOCK_mod_pid_controller_update_CALL_INSTANCE;

typedef struct _CMOCK_mod_sensor_get_data_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_id;
  struct mod_sensor_data* Expected_data;
  int Expected_data_Depth;
  char ReturnThruPtr_data_Used;
  struct mod_sensor_data* ReturnThruPtr_data_Val;
  size_t ReturnThruPtr_data_Size;
  char IgnoreArg_id;
  char IgnoreArg_data;

} CMOCK_mod_sensor_get_data_CALL_INSTANCE;

static struct Mockmod_thermal_power_estimator_extraInstance
{
  char mod_pid_controller_update_IgnoreBool;
  int mod_pid_controller_update_FinalReturn;
  char mod_pid_controller_update_CallbackBool;
  CMOCK_mod_pid_controller_update_CALLBACK mod_pid_controller_update_CallbackFunctionPointer;
  int mod_pid_controller_update_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE mod_pid_controller_update_CallInstance;
  char mod_sensor_get_data_IgnoreBool;
  int mod_sensor_get_data_FinalReturn;
  char mod_sensor_get_data_CallbackBool;
  CMOCK_mod_sensor_get_data_CALLBACK mod_sensor_get_data_CallbackFunctionPointer;
  int mod_sensor_get_data_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE mod_sensor_get_data_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_thermal_power_estimator_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.mod_pid_controller_update_CallInstance;
  if (Mock.mod_pid_controller_update_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mod_pid_controller_update);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.mod_pid_controller_update_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.mod_sensor_get_data_CallInstance;
  if (Mock.mod_sensor_get_data_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mod_sensor_get_data);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.mod_sensor_get_data_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_thermal_power_estimator_extra_Init(void)
{
  Mockmod_thermal_power_estimator_extra_Destroy();
}

void Mockmod_thermal_power_estimator_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int mod_pid_controller_update(fwk_id_t id, int64_t input, int64_t* output)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mod_pid_controller_update_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mod_pid_controller_update);
  cmock_call_instance = (CMOCK_mod_pid_controller_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mod_pid_controller_update_CallInstance);
  Mock.mod_pid_controller_update_CallInstance = CMock_Guts_MemNext(Mock.mod_pid_controller_update_CallInstance);
  if (Mock.mod_pid_controller_update_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.mod_pid_controller_update_FinalReturn;
    Mock.mod_pid_controller_update_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.mod_pid_controller_update_CallbackBool &&
      Mock.mod_pid_controller_update_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.mod_pid_controller_update_CallbackFunctionPointer(id, input, output, Mock.mod_pid_controller_update_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_mod_pid_controller_update,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_input)
  {
    UNITY_SET_DETAILS(CMockString_mod_pid_controller_update,CMockString_input);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_input), (void*)(&input), sizeof(int64_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_output)
  {
    UNITY_SET_DETAILS(CMockString_mod_pid_controller_update,CMockString_output);
    if (cmock_call_instance->Expected_output == NULL)
      { UNITY_TEST_ASSERT_NULL(output, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_output), (void*)(output), sizeof(int64_t), cmock_call_instance->Expected_output_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.mod_pid_controller_update_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.mod_pid_controller_update_CallbackFunctionPointer(id, input, output, Mock.mod_pid_controller_update_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_output_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(output, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)output, (void*)cmock_call_instance->ReturnThruPtr_output_Val,
      cmock_call_instance->ReturnThruPtr_output_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mod_pid_controller_update(CMOCK_mod_pid_controller_update_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, int64_t input, int64_t* output, int output_Depth);
void CMockExpectParameters_mod_pid_controller_update(CMOCK_mod_pid_controller_update_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, int64_t input, int64_t* output, int output_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  memcpy((void*)(&cmock_call_instance->Expected_input), (void*)(&input),
         sizeof(int64_t[sizeof(input) == sizeof(int64_t) ? 1 : -1])); /* add int64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_input = 0;
  cmock_call_instance->Expected_output = output;
  cmock_call_instance->Expected_output_Depth = output_Depth;
  cmock_call_instance->IgnoreArg_output = 0;
  cmock_call_instance->ReturnThruPtr_output_Used = 0;
}

void mod_pid_controller_update_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_pid_controller_update_CALL_INSTANCE));
  CMOCK_mod_pid_controller_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_pid_controller_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_pid_controller_update_CallInstance = CMock_Guts_MemChain(Mock.mod_pid_controller_update_CallInstance, cmock_guts_index);
  Mock.mod_pid_controller_update_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.mod_pid_controller_update_IgnoreBool = (char)1;
}

void mod_pid_controller_update_CMockStopIgnore(void)
{
  if(Mock.mod_pid_controller_update_IgnoreBool)
    Mock.mod_pid_controller_update_CallInstance = CMock_Guts_MemNext(Mock.mod_pid_controller_update_CallInstance);
  Mock.mod_pid_controller_update_IgnoreBool = (char)0;
}

void mod_pid_controller_update_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_pid_controller_update_CALL_INSTANCE));
  CMOCK_mod_pid_controller_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_pid_controller_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_pid_controller_update_CallInstance = CMock_Guts_MemChain(Mock.mod_pid_controller_update_CallInstance, cmock_guts_index);
  Mock.mod_pid_controller_update_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void mod_pid_controller_update_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, int64_t input, int64_t* output, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_pid_controller_update_CALL_INSTANCE));
  CMOCK_mod_pid_controller_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_pid_controller_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_pid_controller_update_CallInstance = CMock_Guts_MemChain(Mock.mod_pid_controller_update_CallInstance, cmock_guts_index);
  Mock.mod_pid_controller_update_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mod_pid_controller_update(cmock_call_instance, id, input, output, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mod_pid_controller_update_AddCallback(CMOCK_mod_pid_controller_update_CALLBACK Callback)
{
  Mock.mod_pid_controller_update_IgnoreBool = (char)0;
  Mock.mod_pid_controller_update_CallbackBool = (char)1;
  Mock.mod_pid_controller_update_CallbackFunctionPointer = Callback;
}

void mod_pid_controller_update_Stub(CMOCK_mod_pid_controller_update_CALLBACK Callback)
{
  Mock.mod_pid_controller_update_IgnoreBool = (char)0;
  Mock.mod_pid_controller_update_CallbackBool = (char)0;
  Mock.mod_pid_controller_update_CallbackFunctionPointer = Callback;
}

void mod_pid_controller_update_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, int64_t input, int64_t* output, int output_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_pid_controller_update_CALL_INSTANCE));
  CMOCK_mod_pid_controller_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_pid_controller_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_pid_controller_update_CallInstance = CMock_Guts_MemChain(Mock.mod_pid_controller_update_CallInstance, cmock_guts_index);
  Mock.mod_pid_controller_update_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mod_pid_controller_update(cmock_call_instance, id, input, output, output_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mod_pid_controller_update_CMockReturnMemThruPtr_output(UNITY_LINE_TYPE cmock_line, int64_t* output, size_t cmock_size)
{
  CMOCK_mod_pid_controller_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_pid_controller_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_pid_controller_update_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_output_Used = 1;
  cmock_call_instance->ReturnThruPtr_output_Val = output;
  cmock_call_instance->ReturnThruPtr_output_Size = cmock_size;
}

void mod_pid_controller_update_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_pid_controller_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_pid_controller_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_pid_controller_update_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void mod_pid_controller_update_CMockIgnoreArg_input(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_pid_controller_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_pid_controller_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_pid_controller_update_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_input = 1;
}

void mod_pid_controller_update_CMockIgnoreArg_output(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_pid_controller_update_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_pid_controller_update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_pid_controller_update_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_output = 1;
}

int mod_sensor_get_data(fwk_id_t id, struct mod_sensor_data* data)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mod_sensor_get_data_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mod_sensor_get_data);
  cmock_call_instance = (CMOCK_mod_sensor_get_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mod_sensor_get_data_CallInstance);
  Mock.mod_sensor_get_data_CallInstance = CMock_Guts_MemNext(Mock.mod_sensor_get_data_CallInstance);
  if (Mock.mod_sensor_get_data_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.mod_sensor_get_data_FinalReturn;
    Mock.mod_sensor_get_data_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.mod_sensor_get_data_CallbackBool &&
      Mock.mod_sensor_get_data_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.mod_sensor_get_data_CallbackFunctionPointer(id, data, Mock.mod_sensor_get_data_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_id)
  {
    UNITY_SET_DETAILS(CMockString_mod_sensor_get_data,CMockString_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_id), (void*)(&id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_data)
  {
    UNITY_SET_DETAILS(CMockString_mod_sensor_get_data,CMockString_data);
    if (cmock_call_instance->Expected_data == NULL)
      { UNITY_TEST_ASSERT_NULL(data, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_data), (void*)(data), sizeof(struct mod_sensor_data), cmock_call_instance->Expected_data_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.mod_sensor_get_data_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.mod_sensor_get_data_CallbackFunctionPointer(id, data, Mock.mod_sensor_get_data_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_data_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(data, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)data, (void*)cmock_call_instance->ReturnThruPtr_data_Val,
      cmock_call_instance->ReturnThruPtr_data_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mod_sensor_get_data(CMOCK_mod_sensor_get_data_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, struct mod_sensor_data* data, int data_Depth);
void CMockExpectParameters_mod_sensor_get_data(CMOCK_mod_sensor_get_data_CALL_INSTANCE* cmock_call_instance, fwk_id_t id, struct mod_sensor_data* data, int data_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_id), (void*)(&id),
         sizeof(fwk_id_t[sizeof(id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_id = 0;
  cmock_call_instance->Expected_data = data;
  cmock_call_instance->Expected_data_Depth = data_Depth;
  cmock_call_instance->IgnoreArg_data = 0;
  cmock_call_instance->ReturnThruPtr_data_Used = 0;
}

void mod_sensor_get_data_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_sensor_get_data_CALL_INSTANCE));
  CMOCK_mod_sensor_get_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_sensor_get_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_sensor_get_data_CallInstance = CMock_Guts_MemChain(Mock.mod_sensor_get_data_CallInstance, cmock_guts_index);
  Mock.mod_sensor_get_data_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.mod_sensor_get_data_IgnoreBool = (char)1;
}

void mod_sensor_get_data_CMockStopIgnore(void)
{
  if(Mock.mod_sensor_get_data_IgnoreBool)
    Mock.mod_sensor_get_data_CallInstance = CMock_Guts_MemNext(Mock.mod_sensor_get_data_CallInstance);
  Mock.mod_sensor_get_data_IgnoreBool = (char)0;
}

void mod_sensor_get_data_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_sensor_get_data_CALL_INSTANCE));
  CMOCK_mod_sensor_get_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_sensor_get_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_sensor_get_data_CallInstance = CMock_Guts_MemChain(Mock.mod_sensor_get_data_CallInstance, cmock_guts_index);
  Mock.mod_sensor_get_data_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void mod_sensor_get_data_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, struct mod_sensor_data* data, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_sensor_get_data_CALL_INSTANCE));
  CMOCK_mod_sensor_get_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_sensor_get_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_sensor_get_data_CallInstance = CMock_Guts_MemChain(Mock.mod_sensor_get_data_CallInstance, cmock_guts_index);
  Mock.mod_sensor_get_data_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mod_sensor_get_data(cmock_call_instance, id, data, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mod_sensor_get_data_AddCallback(CMOCK_mod_sensor_get_data_CALLBACK Callback)
{
  Mock.mod_sensor_get_data_IgnoreBool = (char)0;
  Mock.mod_sensor_get_data_CallbackBool = (char)1;
  Mock.mod_sensor_get_data_CallbackFunctionPointer = Callback;
}

void mod_sensor_get_data_Stub(CMOCK_mod_sensor_get_data_CALLBACK Callback)
{
  Mock.mod_sensor_get_data_IgnoreBool = (char)0;
  Mock.mod_sensor_get_data_CallbackBool = (char)0;
  Mock.mod_sensor_get_data_CallbackFunctionPointer = Callback;
}

void mod_sensor_get_data_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t id, struct mod_sensor_data* data, int data_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_sensor_get_data_CALL_INSTANCE));
  CMOCK_mod_sensor_get_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_sensor_get_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_sensor_get_data_CallInstance = CMock_Guts_MemChain(Mock.mod_sensor_get_data_CallInstance, cmock_guts_index);
  Mock.mod_sensor_get_data_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mod_sensor_get_data(cmock_call_instance, id, data, data_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mod_sensor_get_data_CMockReturnMemThruPtr_data(UNITY_LINE_TYPE cmock_line, struct mod_sensor_data* data, size_t cmock_size)
{
  CMOCK_mod_sensor_get_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_sensor_get_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_sensor_get_data_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_data_Used = 1;
  cmock_call_instance->ReturnThruPtr_data_Val = data;
  cmock_call_instance->ReturnThruPtr_data_Size = cmock_size;
}

void mod_sensor_get_data_CMockIgnoreArg_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_sensor_get_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_sensor_get_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_sensor_get_data_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_id = 1;
}

void mod_sensor_get_data_CMockIgnoreArg_data(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_sensor_get_data_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_sensor_get_data_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_sensor_get_data_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_data = 1;
}

