/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_system_coordinator_extra.h"

static const char* CMockString_alarm_id = "alarm_id";
static const char* CMockString_callback = "callback";
static const char* CMockString_microseconds = "microseconds";
static const char* CMockString_param = "param";
static const char* CMockString_phase_api_stub = "phase_api_stub";
static const char* CMockString_start_alarm_api = "start_alarm_api";
static const char* CMockString_type = "type";

typedef struct _CMOCK_phase_api_stub_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;

} CMOCK_phase_api_stub_CALL_INSTANCE;

typedef struct _CMOCK_start_alarm_api_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_alarm_id;
  unsigned int Expected_microseconds;
  enum mod_timer_alarm_type Expected_type;
  cmock_mod_system_coordinator_extra_func_ptr1 Expected_callback;
  uintptr_t Expected_param;
  char IgnoreArg_alarm_id;
  char IgnoreArg_microseconds;
  char IgnoreArg_type;
  char IgnoreArg_callback;
  char IgnoreArg_param;

} CMOCK_start_alarm_api_CALL_INSTANCE;

static struct Mockmod_system_coordinator_extraInstance
{
  char phase_api_stub_IgnoreBool;
  int phase_api_stub_FinalReturn;
  char phase_api_stub_CallbackBool;
  CMOCK_phase_api_stub_CALLBACK phase_api_stub_CallbackFunctionPointer;
  int phase_api_stub_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE phase_api_stub_CallInstance;
  char start_alarm_api_IgnoreBool;
  int start_alarm_api_FinalReturn;
  char start_alarm_api_CallbackBool;
  CMOCK_start_alarm_api_CALLBACK start_alarm_api_CallbackFunctionPointer;
  int start_alarm_api_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE start_alarm_api_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_system_coordinator_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.phase_api_stub_CallInstance;
  if (Mock.phase_api_stub_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_phase_api_stub);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.phase_api_stub_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.start_alarm_api_CallInstance;
  if (Mock.start_alarm_api_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_start_alarm_api);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.start_alarm_api_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_system_coordinator_extra_Init(void)
{
  Mockmod_system_coordinator_extra_Destroy();
}

void Mockmod_system_coordinator_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int phase_api_stub(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_phase_api_stub_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_phase_api_stub);
  cmock_call_instance = (CMOCK_phase_api_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.phase_api_stub_CallInstance);
  Mock.phase_api_stub_CallInstance = CMock_Guts_MemNext(Mock.phase_api_stub_CallInstance);
  if (Mock.phase_api_stub_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.phase_api_stub_FinalReturn;
    Mock.phase_api_stub_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.phase_api_stub_CallbackBool &&
      Mock.phase_api_stub_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.phase_api_stub_CallbackFunctionPointer(Mock.phase_api_stub_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.phase_api_stub_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.phase_api_stub_CallbackFunctionPointer(Mock.phase_api_stub_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void phase_api_stub_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_phase_api_stub_CALL_INSTANCE));
  CMOCK_phase_api_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_phase_api_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.phase_api_stub_CallInstance = CMock_Guts_MemChain(Mock.phase_api_stub_CallInstance, cmock_guts_index);
  Mock.phase_api_stub_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.phase_api_stub_IgnoreBool = (char)1;
}

void phase_api_stub_CMockStopIgnore(void)
{
  if(Mock.phase_api_stub_IgnoreBool)
    Mock.phase_api_stub_CallInstance = CMock_Guts_MemNext(Mock.phase_api_stub_CallInstance);
  Mock.phase_api_stub_IgnoreBool = (char)0;
}

void phase_api_stub_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_phase_api_stub_CALL_INSTANCE));
  CMOCK_phase_api_stub_CALL_INSTANCE* cmock_call_instance = (CMOCK_phase_api_stub_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.phase_api_stub_CallInstance = CMock_Guts_MemChain(Mock.phase_api_stub_CallInstance, cmock_guts_index);
  Mock.phase_api_stub_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void phase_api_stub_AddCallback(CMOCK_phase_api_stub_CALLBACK Callback)
{
  Mock.phase_api_stub_IgnoreBool = (char)0;
  Mock.phase_api_stub_CallbackBool = (char)1;
  Mock.phase_api_stub_CallbackFunctionPointer = Callback;
}

void phase_api_stub_Stub(CMOCK_phase_api_stub_CALLBACK Callback)
{
  Mock.phase_api_stub_IgnoreBool = (char)0;
  Mock.phase_api_stub_CallbackBool = (char)0;
  Mock.phase_api_stub_CallbackFunctionPointer = Callback;
}

int start_alarm_api(fwk_id_t alarm_id, unsigned int microseconds, enum mod_timer_alarm_type type, cmock_mod_system_coordinator_extra_func_ptr1 callback, uintptr_t param)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_start_alarm_api);
  cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.start_alarm_api_CallInstance);
  Mock.start_alarm_api_CallInstance = CMock_Guts_MemNext(Mock.start_alarm_api_CallInstance);
  if (Mock.start_alarm_api_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.start_alarm_api_FinalReturn;
    Mock.start_alarm_api_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.start_alarm_api_CallbackBool &&
      Mock.start_alarm_api_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.start_alarm_api_CallbackFunctionPointer(alarm_id, microseconds, type, callback, param, Mock.start_alarm_api_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_alarm_id)
  {
    UNITY_SET_DETAILS(CMockString_start_alarm_api,CMockString_alarm_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_alarm_id), (void*)(&alarm_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_microseconds)
  {
    UNITY_SET_DETAILS(CMockString_start_alarm_api,CMockString_microseconds);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_microseconds, microseconds, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_type)
  {
    UNITY_SET_DETAILS(CMockString_start_alarm_api,CMockString_type);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_type), (void*)(&type), sizeof(enum mod_timer_alarm_type), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_callback)
  {
    UNITY_SET_DETAILS(CMockString_start_alarm_api,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_callback, callback, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_param)
  {
    UNITY_SET_DETAILS(CMockString_start_alarm_api,CMockString_param);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_param), (void*)(&param), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.start_alarm_api_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.start_alarm_api_CallbackFunctionPointer(alarm_id, microseconds, type, callback, param, Mock.start_alarm_api_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_start_alarm_api(CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance, fwk_id_t alarm_id, unsigned int microseconds, enum mod_timer_alarm_type type, cmock_mod_system_coordinator_extra_func_ptr1 callback, uintptr_t param);
void CMockExpectParameters_start_alarm_api(CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance, fwk_id_t alarm_id, unsigned int microseconds, enum mod_timer_alarm_type type, cmock_mod_system_coordinator_extra_func_ptr1 callback, uintptr_t param)
{
  memcpy((void*)(&cmock_call_instance->Expected_alarm_id), (void*)(&alarm_id),
         sizeof(fwk_id_t[sizeof(alarm_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_alarm_id = 0;
  cmock_call_instance->Expected_microseconds = microseconds;
  cmock_call_instance->IgnoreArg_microseconds = 0;
  memcpy((void*)(&cmock_call_instance->Expected_type), (void*)(&type),
         sizeof(enum mod_timer_alarm_type[sizeof(type) == sizeof(enum mod_timer_alarm_type) ? 1 : -1])); /* add enum mod_timer_alarm_type to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_type = 0;
  memcpy((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback),
         sizeof(cmock_mod_system_coordinator_extra_func_ptr1[sizeof(callback) == sizeof(cmock_mod_system_coordinator_extra_func_ptr1) ? 1 : -1])); /* add cmock_mod_system_coordinator_extra_func_ptr1 to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_callback = 0;
  memcpy((void*)(&cmock_call_instance->Expected_param), (void*)(&param),
         sizeof(uintptr_t[sizeof(param) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_param = 0;
}

void start_alarm_api_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_start_alarm_api_CALL_INSTANCE));
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.start_alarm_api_CallInstance = CMock_Guts_MemChain(Mock.start_alarm_api_CallInstance, cmock_guts_index);
  Mock.start_alarm_api_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.start_alarm_api_IgnoreBool = (char)1;
}

void start_alarm_api_CMockStopIgnore(void)
{
  if(Mock.start_alarm_api_IgnoreBool)
    Mock.start_alarm_api_CallInstance = CMock_Guts_MemNext(Mock.start_alarm_api_CallInstance);
  Mock.start_alarm_api_IgnoreBool = (char)0;
}

void start_alarm_api_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_start_alarm_api_CALL_INSTANCE));
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.start_alarm_api_CallInstance = CMock_Guts_MemChain(Mock.start_alarm_api_CallInstance, cmock_guts_index);
  Mock.start_alarm_api_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void start_alarm_api_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t alarm_id, unsigned int microseconds, enum mod_timer_alarm_type type, cmock_mod_system_coordinator_extra_func_ptr1 callback, uintptr_t param, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_start_alarm_api_CALL_INSTANCE));
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.start_alarm_api_CallInstance = CMock_Guts_MemChain(Mock.start_alarm_api_CallInstance, cmock_guts_index);
  Mock.start_alarm_api_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_start_alarm_api(cmock_call_instance, alarm_id, microseconds, type, callback, param);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void start_alarm_api_AddCallback(CMOCK_start_alarm_api_CALLBACK Callback)
{
  Mock.start_alarm_api_IgnoreBool = (char)0;
  Mock.start_alarm_api_CallbackBool = (char)1;
  Mock.start_alarm_api_CallbackFunctionPointer = Callback;
}

void start_alarm_api_Stub(CMOCK_start_alarm_api_CALLBACK Callback)
{
  Mock.start_alarm_api_IgnoreBool = (char)0;
  Mock.start_alarm_api_CallbackBool = (char)0;
  Mock.start_alarm_api_CallbackFunctionPointer = Callback;
}

void start_alarm_api_CMockIgnoreArg_alarm_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_alarm_api_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_alarm_id = 1;
}

void start_alarm_api_CMockIgnoreArg_microseconds(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_alarm_api_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_microseconds = 1;
}

void start_alarm_api_CMockIgnoreArg_type(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_alarm_api_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_type = 1;
}

void start_alarm_api_CMockIgnoreArg_callback(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_alarm_api_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_callback = 1;
}

void start_alarm_api_CMockIgnoreArg_param(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_alarm_api_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_param = 1;
}

