/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMOD_PINCTRL_DRV_EXTRA_H
#define _MOCKMOD_PINCTRL_DRV_EXTRA_H

#include "unity.h"
#include "mod_pinctrl_drv_extra.h"

/* Ignore the following warnings, since we are copying code */
#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic push
#endif
#if !defined(__clang__)
#pragma GCC diagnostic ignored "-Wpragmas"
#endif
#pragma GCC diagnostic ignored "-Wunknown-pragmas"
#pragma GCC diagnostic ignored "-Wduplicate-decl-specifier"
#endif

void Mockmod_pinctrl_drv_extra_Init(void);
void Mockmod_pinctrl_drv_extra_Destroy(void);
void Mockmod_pinctrl_drv_extra_Verify(void);




#define get_pin_function_IgnoreAndReturn(cmock_retval) get_pin_function_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_pin_function_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_pin_function_StopIgnore() get_pin_function_CMockStopIgnore()
void get_pin_function_CMockStopIgnore(void);
#define get_pin_function_ExpectAnyArgsAndReturn(cmock_retval) get_pin_function_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void get_pin_function_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_pin_function_ExpectAndReturn(pin_id, function_id, cmock_retval) get_pin_function_CMockExpectAndReturn(__LINE__, pin_id, function_id, cmock_retval)
void get_pin_function_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, uint32_t* function_id, int cmock_to_return);
typedef int (* CMOCK_get_pin_function_CALLBACK)(uint16_t pin_id, uint32_t* function_id, int cmock_num_calls);
void get_pin_function_AddCallback(CMOCK_get_pin_function_CALLBACK Callback);
void get_pin_function_Stub(CMOCK_get_pin_function_CALLBACK Callback);
#define get_pin_function_StubWithCallback get_pin_function_Stub
#define get_pin_function_ExpectWithArrayAndReturn(pin_id, function_id, function_id_Depth, cmock_retval) get_pin_function_CMockExpectWithArrayAndReturn(__LINE__, pin_id, function_id, function_id_Depth, cmock_retval)
void get_pin_function_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, uint32_t* function_id, int function_id_Depth, int cmock_to_return);
#define get_pin_function_ReturnThruPtr_function_id(function_id) get_pin_function_CMockReturnMemThruPtr_function_id(__LINE__, function_id, sizeof(uint32_t))
#define get_pin_function_ReturnArrayThruPtr_function_id(function_id, cmock_len) get_pin_function_CMockReturnMemThruPtr_function_id(__LINE__, function_id, cmock_len * sizeof(*function_id))
#define get_pin_function_ReturnMemThruPtr_function_id(function_id, cmock_size) get_pin_function_CMockReturnMemThruPtr_function_id(__LINE__, function_id, cmock_size)
void get_pin_function_CMockReturnMemThruPtr_function_id(UNITY_LINE_TYPE cmock_line, uint32_t* function_id, size_t cmock_size);
#define get_pin_function_IgnoreArg_pin_id() get_pin_function_CMockIgnoreArg_pin_id(__LINE__)
void get_pin_function_CMockIgnoreArg_pin_id(UNITY_LINE_TYPE cmock_line);
#define get_pin_function_IgnoreArg_function_id() get_pin_function_CMockIgnoreArg_function_id(__LINE__)
void get_pin_function_CMockIgnoreArg_function_id(UNITY_LINE_TYPE cmock_line);
#define set_pin_function_IgnoreAndReturn(cmock_retval) set_pin_function_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void set_pin_function_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define set_pin_function_StopIgnore() set_pin_function_CMockStopIgnore()
void set_pin_function_CMockStopIgnore(void);
#define set_pin_function_ExpectAnyArgsAndReturn(cmock_retval) set_pin_function_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void set_pin_function_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define set_pin_function_ExpectAndReturn(pin_id, function_id, cmock_retval) set_pin_function_CMockExpectAndReturn(__LINE__, pin_id, function_id, cmock_retval)
void set_pin_function_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, uint32_t function_id, int cmock_to_return);
typedef int (* CMOCK_set_pin_function_CALLBACK)(uint16_t pin_id, uint32_t function_id, int cmock_num_calls);
void set_pin_function_AddCallback(CMOCK_set_pin_function_CALLBACK Callback);
void set_pin_function_Stub(CMOCK_set_pin_function_CALLBACK Callback);
#define set_pin_function_StubWithCallback set_pin_function_Stub
#define set_pin_function_IgnoreArg_pin_id() set_pin_function_CMockIgnoreArg_pin_id(__LINE__)
void set_pin_function_CMockIgnoreArg_pin_id(UNITY_LINE_TYPE cmock_line);
#define set_pin_function_IgnoreArg_function_id() set_pin_function_CMockIgnoreArg_function_id(__LINE__)
void set_pin_function_CMockIgnoreArg_function_id(UNITY_LINE_TYPE cmock_line);
#define set_pin_configuration_IgnoreAndReturn(cmock_retval) set_pin_configuration_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void set_pin_configuration_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define set_pin_configuration_StopIgnore() set_pin_configuration_CMockStopIgnore()
void set_pin_configuration_CMockStopIgnore(void);
#define set_pin_configuration_ExpectAnyArgsAndReturn(cmock_retval) set_pin_configuration_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void set_pin_configuration_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define set_pin_configuration_ExpectAndReturn(pin_id, pin_config, cmock_retval) set_pin_configuration_CMockExpectAndReturn(__LINE__, pin_id, pin_config, cmock_retval)
void set_pin_configuration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, const struct mod_pinctrl_drv_pin_configuration* pin_config, int cmock_to_return);
typedef int (* CMOCK_set_pin_configuration_CALLBACK)(uint16_t pin_id, const struct mod_pinctrl_drv_pin_configuration* pin_config, int cmock_num_calls);
void set_pin_configuration_AddCallback(CMOCK_set_pin_configuration_CALLBACK Callback);
void set_pin_configuration_Stub(CMOCK_set_pin_configuration_CALLBACK Callback);
#define set_pin_configuration_StubWithCallback set_pin_configuration_Stub
#define set_pin_configuration_ExpectWithArrayAndReturn(pin_id, pin_config, pin_config_Depth, cmock_retval) set_pin_configuration_CMockExpectWithArrayAndReturn(__LINE__, pin_id, pin_config, pin_config_Depth, cmock_retval)
void set_pin_configuration_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, const struct mod_pinctrl_drv_pin_configuration* pin_config, int pin_config_Depth, int cmock_to_return);
#define set_pin_configuration_IgnoreArg_pin_id() set_pin_configuration_CMockIgnoreArg_pin_id(__LINE__)
void set_pin_configuration_CMockIgnoreArg_pin_id(UNITY_LINE_TYPE cmock_line);
#define set_pin_configuration_IgnoreArg_pin_config() set_pin_configuration_CMockIgnoreArg_pin_config(__LINE__)
void set_pin_configuration_CMockIgnoreArg_pin_config(UNITY_LINE_TYPE cmock_line);
#define get_pin_configuration_IgnoreAndReturn(cmock_retval) get_pin_configuration_CMockIgnoreAndReturn(__LINE__, cmock_retval)
void get_pin_configuration_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_pin_configuration_StopIgnore() get_pin_configuration_CMockStopIgnore()
void get_pin_configuration_CMockStopIgnore(void);
#define get_pin_configuration_ExpectAnyArgsAndReturn(cmock_retval) get_pin_configuration_CMockExpectAnyArgsAndReturn(__LINE__, cmock_retval)
void get_pin_configuration_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return);
#define get_pin_configuration_ExpectAndReturn(pin_id, pin_config, cmock_retval) get_pin_configuration_CMockExpectAndReturn(__LINE__, pin_id, pin_config, cmock_retval)
void get_pin_configuration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, struct mod_pinctrl_drv_pin_configuration* pin_config, int cmock_to_return);
typedef int (* CMOCK_get_pin_configuration_CALLBACK)(uint16_t pin_id, struct mod_pinctrl_drv_pin_configuration* pin_config, int cmock_num_calls);
void get_pin_configuration_AddCallback(CMOCK_get_pin_configuration_CALLBACK Callback);
void get_pin_configuration_Stub(CMOCK_get_pin_configuration_CALLBACK Callback);
#define get_pin_configuration_StubWithCallback get_pin_configuration_Stub
#define get_pin_configuration_ExpectWithArrayAndReturn(pin_id, pin_config, pin_config_Depth, cmock_retval) get_pin_configuration_CMockExpectWithArrayAndReturn(__LINE__, pin_id, pin_config, pin_config_Depth, cmock_retval)
void get_pin_configuration_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, struct mod_pinctrl_drv_pin_configuration* pin_config, int pin_config_Depth, int cmock_to_return);
#define get_pin_configuration_ReturnThruPtr_pin_config(pin_config) get_pin_configuration_CMockReturnMemThruPtr_pin_config(__LINE__, pin_config, sizeof(struct mod_pinctrl_drv_pin_configuration))
#define get_pin_configuration_ReturnArrayThruPtr_pin_config(pin_config, cmock_len) get_pin_configuration_CMockReturnMemThruPtr_pin_config(__LINE__, pin_config, cmock_len * sizeof(*pin_config))
#define get_pin_configuration_ReturnMemThruPtr_pin_config(pin_config, cmock_size) get_pin_configuration_CMockReturnMemThruPtr_pin_config(__LINE__, pin_config, cmock_size)
void get_pin_configuration_CMockReturnMemThruPtr_pin_config(UNITY_LINE_TYPE cmock_line, struct mod_pinctrl_drv_pin_configuration* pin_config, size_t cmock_size);
#define get_pin_configuration_IgnoreArg_pin_id() get_pin_configuration_CMockIgnoreArg_pin_id(__LINE__)
void get_pin_configuration_CMockIgnoreArg_pin_id(UNITY_LINE_TYPE cmock_line);
#define get_pin_configuration_IgnoreArg_pin_config() get_pin_configuration_CMockIgnoreArg_pin_config(__LINE__)
void get_pin_configuration_CMockIgnoreArg_pin_config(UNITY_LINE_TYPE cmock_line);

#if defined(__GNUC__) && !defined(__ICC) && !defined(__TMS470__)
#if __GNUC__ > 4 || (__GNUC__ == 4 && (__GNUC_MINOR__ > 6 || (__GNUC_MINOR__ == 6 && __GNUC_PATCHLEVEL__ > 0)))
#pragma GCC diagnostic pop
#endif
#endif

#endif
