/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_pinctrl_drv_extra.h"

static const char* CMockString_function_id = "function_id";
static const char* CMockString_get_pin_configuration = "get_pin_configuration";
static const char* CMockString_get_pin_function = "get_pin_function";
static const char* CMockString_pin_config = "pin_config";
static const char* CMockString_pin_id = "pin_id";
static const char* CMockString_set_pin_configuration = "set_pin_configuration";
static const char* CMockString_set_pin_function = "set_pin_function";

typedef struct _CMOCK_get_pin_function_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  uint16_t Expected_pin_id;
  uint32_t* Expected_function_id;
  int Expected_function_id_Depth;
  char ReturnThruPtr_function_id_Used;
  uint32_t* ReturnThruPtr_function_id_Val;
  size_t ReturnThruPtr_function_id_Size;
  char IgnoreArg_pin_id;
  char IgnoreArg_function_id;

} CMOCK_get_pin_function_CALL_INSTANCE;

typedef struct _CMOCK_set_pin_function_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  uint16_t Expected_pin_id;
  uint32_t Expected_function_id;
  char IgnoreArg_pin_id;
  char IgnoreArg_function_id;

} CMOCK_set_pin_function_CALL_INSTANCE;

typedef struct _CMOCK_set_pin_configuration_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  uint16_t Expected_pin_id;
  const struct mod_pinctrl_drv_pin_configuration* Expected_pin_config;
  int Expected_pin_config_Depth;
  char IgnoreArg_pin_id;
  char IgnoreArg_pin_config;

} CMOCK_set_pin_configuration_CALL_INSTANCE;

typedef struct _CMOCK_get_pin_configuration_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  uint16_t Expected_pin_id;
  struct mod_pinctrl_drv_pin_configuration* Expected_pin_config;
  int Expected_pin_config_Depth;
  char ReturnThruPtr_pin_config_Used;
  struct mod_pinctrl_drv_pin_configuration* ReturnThruPtr_pin_config_Val;
  size_t ReturnThruPtr_pin_config_Size;
  char IgnoreArg_pin_id;
  char IgnoreArg_pin_config;

} CMOCK_get_pin_configuration_CALL_INSTANCE;

static struct Mockmod_pinctrl_drv_extraInstance
{
  char get_pin_function_IgnoreBool;
  int get_pin_function_FinalReturn;
  char get_pin_function_CallbackBool;
  CMOCK_get_pin_function_CALLBACK get_pin_function_CallbackFunctionPointer;
  int get_pin_function_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_pin_function_CallInstance;
  char set_pin_function_IgnoreBool;
  int set_pin_function_FinalReturn;
  char set_pin_function_CallbackBool;
  CMOCK_set_pin_function_CALLBACK set_pin_function_CallbackFunctionPointer;
  int set_pin_function_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE set_pin_function_CallInstance;
  char set_pin_configuration_IgnoreBool;
  int set_pin_configuration_FinalReturn;
  char set_pin_configuration_CallbackBool;
  CMOCK_set_pin_configuration_CALLBACK set_pin_configuration_CallbackFunctionPointer;
  int set_pin_configuration_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE set_pin_configuration_CallInstance;
  char get_pin_configuration_IgnoreBool;
  int get_pin_configuration_FinalReturn;
  char get_pin_configuration_CallbackBool;
  CMOCK_get_pin_configuration_CALLBACK get_pin_configuration_CallbackFunctionPointer;
  int get_pin_configuration_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE get_pin_configuration_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_pinctrl_drv_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.get_pin_function_CallInstance;
  if (Mock.get_pin_function_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_pin_function);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_pin_function_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.set_pin_function_CallInstance;
  if (Mock.set_pin_function_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_set_pin_function);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.set_pin_function_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.set_pin_configuration_CallInstance;
  if (Mock.set_pin_configuration_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_set_pin_configuration);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.set_pin_configuration_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.get_pin_configuration_CallInstance;
  if (Mock.get_pin_configuration_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_get_pin_configuration);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.get_pin_configuration_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_pinctrl_drv_extra_Init(void)
{
  Mockmod_pinctrl_drv_extra_Destroy();
}

void Mockmod_pinctrl_drv_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int get_pin_function(uint16_t pin_id, uint32_t* function_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_pin_function_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_pin_function);
  cmock_call_instance = (CMOCK_get_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_pin_function_CallInstance);
  Mock.get_pin_function_CallInstance = CMock_Guts_MemNext(Mock.get_pin_function_CallInstance);
  if (Mock.get_pin_function_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_pin_function_FinalReturn;
    Mock.get_pin_function_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_pin_function_CallbackBool &&
      Mock.get_pin_function_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.get_pin_function_CallbackFunctionPointer(pin_id, function_id, Mock.get_pin_function_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_pin_id)
  {
    UNITY_SET_DETAILS(CMockString_get_pin_function,CMockString_pin_id);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_pin_id, pin_id, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_function_id)
  {
    UNITY_SET_DETAILS(CMockString_get_pin_function,CMockString_function_id);
    if (cmock_call_instance->Expected_function_id == NULL)
      { UNITY_TEST_ASSERT_NULL(function_id, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_function_id, function_id, cmock_call_instance->Expected_function_id_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.get_pin_function_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_pin_function_CallbackFunctionPointer(pin_id, function_id, Mock.get_pin_function_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_function_id_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(function_id, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)function_id, (void*)cmock_call_instance->ReturnThruPtr_function_id_Val,
      cmock_call_instance->ReturnThruPtr_function_id_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_pin_function(CMOCK_get_pin_function_CALL_INSTANCE* cmock_call_instance, uint16_t pin_id, uint32_t* function_id, int function_id_Depth);
void CMockExpectParameters_get_pin_function(CMOCK_get_pin_function_CALL_INSTANCE* cmock_call_instance, uint16_t pin_id, uint32_t* function_id, int function_id_Depth)
{
  cmock_call_instance->Expected_pin_id = pin_id;
  cmock_call_instance->IgnoreArg_pin_id = 0;
  cmock_call_instance->Expected_function_id = function_id;
  cmock_call_instance->Expected_function_id_Depth = function_id_Depth;
  cmock_call_instance->IgnoreArg_function_id = 0;
  cmock_call_instance->ReturnThruPtr_function_id_Used = 0;
}

void get_pin_function_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_pin_function_CALL_INSTANCE));
  CMOCK_get_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_pin_function_CallInstance = CMock_Guts_MemChain(Mock.get_pin_function_CallInstance, cmock_guts_index);
  Mock.get_pin_function_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_pin_function_IgnoreBool = (char)1;
}

void get_pin_function_CMockStopIgnore(void)
{
  if(Mock.get_pin_function_IgnoreBool)
    Mock.get_pin_function_CallInstance = CMock_Guts_MemNext(Mock.get_pin_function_CallInstance);
  Mock.get_pin_function_IgnoreBool = (char)0;
}

void get_pin_function_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_pin_function_CALL_INSTANCE));
  CMOCK_get_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_pin_function_CallInstance = CMock_Guts_MemChain(Mock.get_pin_function_CallInstance, cmock_guts_index);
  Mock.get_pin_function_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_pin_function_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, uint32_t* function_id, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_pin_function_CALL_INSTANCE));
  CMOCK_get_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_pin_function_CallInstance = CMock_Guts_MemChain(Mock.get_pin_function_CallInstance, cmock_guts_index);
  Mock.get_pin_function_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_pin_function(cmock_call_instance, pin_id, function_id, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_pin_function_AddCallback(CMOCK_get_pin_function_CALLBACK Callback)
{
  Mock.get_pin_function_IgnoreBool = (char)0;
  Mock.get_pin_function_CallbackBool = (char)1;
  Mock.get_pin_function_CallbackFunctionPointer = Callback;
}

void get_pin_function_Stub(CMOCK_get_pin_function_CALLBACK Callback)
{
  Mock.get_pin_function_IgnoreBool = (char)0;
  Mock.get_pin_function_CallbackBool = (char)0;
  Mock.get_pin_function_CallbackFunctionPointer = Callback;
}

void get_pin_function_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, uint32_t* function_id, int function_id_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_pin_function_CALL_INSTANCE));
  CMOCK_get_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_pin_function_CallInstance = CMock_Guts_MemChain(Mock.get_pin_function_CallInstance, cmock_guts_index);
  Mock.get_pin_function_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_pin_function(cmock_call_instance, pin_id, function_id, function_id_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_pin_function_CMockReturnMemThruPtr_function_id(UNITY_LINE_TYPE cmock_line, uint32_t* function_id, size_t cmock_size)
{
  CMOCK_get_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_pin_function_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_function_id_Used = 1;
  cmock_call_instance->ReturnThruPtr_function_id_Val = function_id;
  cmock_call_instance->ReturnThruPtr_function_id_Size = cmock_size;
}

void get_pin_function_CMockIgnoreArg_pin_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_pin_function_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pin_id = 1;
}

void get_pin_function_CMockIgnoreArg_function_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_pin_function_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_function_id = 1;
}

int set_pin_function(uint16_t pin_id, uint32_t function_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_set_pin_function_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_set_pin_function);
  cmock_call_instance = (CMOCK_set_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.set_pin_function_CallInstance);
  Mock.set_pin_function_CallInstance = CMock_Guts_MemNext(Mock.set_pin_function_CallInstance);
  if (Mock.set_pin_function_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.set_pin_function_FinalReturn;
    Mock.set_pin_function_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.set_pin_function_CallbackBool &&
      Mock.set_pin_function_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.set_pin_function_CallbackFunctionPointer(pin_id, function_id, Mock.set_pin_function_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_pin_id)
  {
    UNITY_SET_DETAILS(CMockString_set_pin_function,CMockString_pin_id);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_pin_id, pin_id, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_function_id)
  {
    UNITY_SET_DETAILS(CMockString_set_pin_function,CMockString_function_id);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_function_id, function_id, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.set_pin_function_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.set_pin_function_CallbackFunctionPointer(pin_id, function_id, Mock.set_pin_function_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_set_pin_function(CMOCK_set_pin_function_CALL_INSTANCE* cmock_call_instance, uint16_t pin_id, uint32_t function_id);
void CMockExpectParameters_set_pin_function(CMOCK_set_pin_function_CALL_INSTANCE* cmock_call_instance, uint16_t pin_id, uint32_t function_id)
{
  cmock_call_instance->Expected_pin_id = pin_id;
  cmock_call_instance->IgnoreArg_pin_id = 0;
  cmock_call_instance->Expected_function_id = function_id;
  cmock_call_instance->IgnoreArg_function_id = 0;
}

void set_pin_function_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_pin_function_CALL_INSTANCE));
  CMOCK_set_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_pin_function_CallInstance = CMock_Guts_MemChain(Mock.set_pin_function_CallInstance, cmock_guts_index);
  Mock.set_pin_function_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.set_pin_function_IgnoreBool = (char)1;
}

void set_pin_function_CMockStopIgnore(void)
{
  if(Mock.set_pin_function_IgnoreBool)
    Mock.set_pin_function_CallInstance = CMock_Guts_MemNext(Mock.set_pin_function_CallInstance);
  Mock.set_pin_function_IgnoreBool = (char)0;
}

void set_pin_function_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_pin_function_CALL_INSTANCE));
  CMOCK_set_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_pin_function_CallInstance = CMock_Guts_MemChain(Mock.set_pin_function_CallInstance, cmock_guts_index);
  Mock.set_pin_function_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void set_pin_function_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, uint32_t function_id, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_pin_function_CALL_INSTANCE));
  CMOCK_set_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_pin_function_CallInstance = CMock_Guts_MemChain(Mock.set_pin_function_CallInstance, cmock_guts_index);
  Mock.set_pin_function_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_set_pin_function(cmock_call_instance, pin_id, function_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void set_pin_function_AddCallback(CMOCK_set_pin_function_CALLBACK Callback)
{
  Mock.set_pin_function_IgnoreBool = (char)0;
  Mock.set_pin_function_CallbackBool = (char)1;
  Mock.set_pin_function_CallbackFunctionPointer = Callback;
}

void set_pin_function_Stub(CMOCK_set_pin_function_CALLBACK Callback)
{
  Mock.set_pin_function_IgnoreBool = (char)0;
  Mock.set_pin_function_CallbackBool = (char)0;
  Mock.set_pin_function_CallbackFunctionPointer = Callback;
}

void set_pin_function_CMockIgnoreArg_pin_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_set_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.set_pin_function_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pin_id = 1;
}

void set_pin_function_CMockIgnoreArg_function_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_set_pin_function_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_pin_function_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.set_pin_function_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_function_id = 1;
}

int set_pin_configuration(uint16_t pin_id, const struct mod_pinctrl_drv_pin_configuration* pin_config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_set_pin_configuration_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_set_pin_configuration);
  cmock_call_instance = (CMOCK_set_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.set_pin_configuration_CallInstance);
  Mock.set_pin_configuration_CallInstance = CMock_Guts_MemNext(Mock.set_pin_configuration_CallInstance);
  if (Mock.set_pin_configuration_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.set_pin_configuration_FinalReturn;
    Mock.set_pin_configuration_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.set_pin_configuration_CallbackBool &&
      Mock.set_pin_configuration_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.set_pin_configuration_CallbackFunctionPointer(pin_id, pin_config, Mock.set_pin_configuration_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_pin_id)
  {
    UNITY_SET_DETAILS(CMockString_set_pin_configuration,CMockString_pin_id);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_pin_id, pin_id, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_pin_config)
  {
    UNITY_SET_DETAILS(CMockString_set_pin_configuration,CMockString_pin_config);
    if (cmock_call_instance->Expected_pin_config == NULL)
      { UNITY_TEST_ASSERT_NULL(pin_config, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_pin_config), (void*)(pin_config), sizeof(const struct mod_pinctrl_drv_pin_configuration), cmock_call_instance->Expected_pin_config_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.set_pin_configuration_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.set_pin_configuration_CallbackFunctionPointer(pin_id, pin_config, Mock.set_pin_configuration_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_set_pin_configuration(CMOCK_set_pin_configuration_CALL_INSTANCE* cmock_call_instance, uint16_t pin_id, const struct mod_pinctrl_drv_pin_configuration* pin_config, int pin_config_Depth);
void CMockExpectParameters_set_pin_configuration(CMOCK_set_pin_configuration_CALL_INSTANCE* cmock_call_instance, uint16_t pin_id, const struct mod_pinctrl_drv_pin_configuration* pin_config, int pin_config_Depth)
{
  cmock_call_instance->Expected_pin_id = pin_id;
  cmock_call_instance->IgnoreArg_pin_id = 0;
  cmock_call_instance->Expected_pin_config = pin_config;
  cmock_call_instance->Expected_pin_config_Depth = pin_config_Depth;
  cmock_call_instance->IgnoreArg_pin_config = 0;
}

void set_pin_configuration_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_pin_configuration_CALL_INSTANCE));
  CMOCK_set_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_pin_configuration_CallInstance = CMock_Guts_MemChain(Mock.set_pin_configuration_CallInstance, cmock_guts_index);
  Mock.set_pin_configuration_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.set_pin_configuration_IgnoreBool = (char)1;
}

void set_pin_configuration_CMockStopIgnore(void)
{
  if(Mock.set_pin_configuration_IgnoreBool)
    Mock.set_pin_configuration_CallInstance = CMock_Guts_MemNext(Mock.set_pin_configuration_CallInstance);
  Mock.set_pin_configuration_IgnoreBool = (char)0;
}

void set_pin_configuration_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_pin_configuration_CALL_INSTANCE));
  CMOCK_set_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_pin_configuration_CallInstance = CMock_Guts_MemChain(Mock.set_pin_configuration_CallInstance, cmock_guts_index);
  Mock.set_pin_configuration_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void set_pin_configuration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, const struct mod_pinctrl_drv_pin_configuration* pin_config, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_pin_configuration_CALL_INSTANCE));
  CMOCK_set_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_pin_configuration_CallInstance = CMock_Guts_MemChain(Mock.set_pin_configuration_CallInstance, cmock_guts_index);
  Mock.set_pin_configuration_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_set_pin_configuration(cmock_call_instance, pin_id, pin_config, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void set_pin_configuration_AddCallback(CMOCK_set_pin_configuration_CALLBACK Callback)
{
  Mock.set_pin_configuration_IgnoreBool = (char)0;
  Mock.set_pin_configuration_CallbackBool = (char)1;
  Mock.set_pin_configuration_CallbackFunctionPointer = Callback;
}

void set_pin_configuration_Stub(CMOCK_set_pin_configuration_CALLBACK Callback)
{
  Mock.set_pin_configuration_IgnoreBool = (char)0;
  Mock.set_pin_configuration_CallbackBool = (char)0;
  Mock.set_pin_configuration_CallbackFunctionPointer = Callback;
}

void set_pin_configuration_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, const struct mod_pinctrl_drv_pin_configuration* pin_config, int pin_config_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_set_pin_configuration_CALL_INSTANCE));
  CMOCK_set_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.set_pin_configuration_CallInstance = CMock_Guts_MemChain(Mock.set_pin_configuration_CallInstance, cmock_guts_index);
  Mock.set_pin_configuration_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_set_pin_configuration(cmock_call_instance, pin_id, pin_config, pin_config_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void set_pin_configuration_CMockIgnoreArg_pin_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_set_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.set_pin_configuration_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pin_id = 1;
}

void set_pin_configuration_CMockIgnoreArg_pin_config(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_set_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_set_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.set_pin_configuration_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pin_config = 1;
}

int get_pin_configuration(uint16_t pin_id, struct mod_pinctrl_drv_pin_configuration* pin_config)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_get_pin_configuration_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_get_pin_configuration);
  cmock_call_instance = (CMOCK_get_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.get_pin_configuration_CallInstance);
  Mock.get_pin_configuration_CallInstance = CMock_Guts_MemNext(Mock.get_pin_configuration_CallInstance);
  if (Mock.get_pin_configuration_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.get_pin_configuration_FinalReturn;
    Mock.get_pin_configuration_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.get_pin_configuration_CallbackBool &&
      Mock.get_pin_configuration_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.get_pin_configuration_CallbackFunctionPointer(pin_id, pin_config, Mock.get_pin_configuration_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_pin_id)
  {
    UNITY_SET_DETAILS(CMockString_get_pin_configuration,CMockString_pin_id);
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_pin_id, pin_id, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_pin_config)
  {
    UNITY_SET_DETAILS(CMockString_get_pin_configuration,CMockString_pin_config);
    if (cmock_call_instance->Expected_pin_config == NULL)
      { UNITY_TEST_ASSERT_NULL(pin_config, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_pin_config), (void*)(pin_config), sizeof(struct mod_pinctrl_drv_pin_configuration), cmock_call_instance->Expected_pin_config_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.get_pin_configuration_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.get_pin_configuration_CallbackFunctionPointer(pin_id, pin_config, Mock.get_pin_configuration_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_pin_config_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(pin_config, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)pin_config, (void*)cmock_call_instance->ReturnThruPtr_pin_config_Val,
      cmock_call_instance->ReturnThruPtr_pin_config_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_get_pin_configuration(CMOCK_get_pin_configuration_CALL_INSTANCE* cmock_call_instance, uint16_t pin_id, struct mod_pinctrl_drv_pin_configuration* pin_config, int pin_config_Depth);
void CMockExpectParameters_get_pin_configuration(CMOCK_get_pin_configuration_CALL_INSTANCE* cmock_call_instance, uint16_t pin_id, struct mod_pinctrl_drv_pin_configuration* pin_config, int pin_config_Depth)
{
  cmock_call_instance->Expected_pin_id = pin_id;
  cmock_call_instance->IgnoreArg_pin_id = 0;
  cmock_call_instance->Expected_pin_config = pin_config;
  cmock_call_instance->Expected_pin_config_Depth = pin_config_Depth;
  cmock_call_instance->IgnoreArg_pin_config = 0;
  cmock_call_instance->ReturnThruPtr_pin_config_Used = 0;
}

void get_pin_configuration_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_pin_configuration_CALL_INSTANCE));
  CMOCK_get_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_pin_configuration_CallInstance = CMock_Guts_MemChain(Mock.get_pin_configuration_CallInstance, cmock_guts_index);
  Mock.get_pin_configuration_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.get_pin_configuration_IgnoreBool = (char)1;
}

void get_pin_configuration_CMockStopIgnore(void)
{
  if(Mock.get_pin_configuration_IgnoreBool)
    Mock.get_pin_configuration_CallInstance = CMock_Guts_MemNext(Mock.get_pin_configuration_CallInstance);
  Mock.get_pin_configuration_IgnoreBool = (char)0;
}

void get_pin_configuration_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_pin_configuration_CALL_INSTANCE));
  CMOCK_get_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_pin_configuration_CallInstance = CMock_Guts_MemChain(Mock.get_pin_configuration_CallInstance, cmock_guts_index);
  Mock.get_pin_configuration_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void get_pin_configuration_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, struct mod_pinctrl_drv_pin_configuration* pin_config, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_pin_configuration_CALL_INSTANCE));
  CMOCK_get_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_pin_configuration_CallInstance = CMock_Guts_MemChain(Mock.get_pin_configuration_CallInstance, cmock_guts_index);
  Mock.get_pin_configuration_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_pin_configuration(cmock_call_instance, pin_id, pin_config, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_pin_configuration_AddCallback(CMOCK_get_pin_configuration_CALLBACK Callback)
{
  Mock.get_pin_configuration_IgnoreBool = (char)0;
  Mock.get_pin_configuration_CallbackBool = (char)1;
  Mock.get_pin_configuration_CallbackFunctionPointer = Callback;
}

void get_pin_configuration_Stub(CMOCK_get_pin_configuration_CALLBACK Callback)
{
  Mock.get_pin_configuration_IgnoreBool = (char)0;
  Mock.get_pin_configuration_CallbackBool = (char)0;
  Mock.get_pin_configuration_CallbackFunctionPointer = Callback;
}

void get_pin_configuration_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint16_t pin_id, struct mod_pinctrl_drv_pin_configuration* pin_config, int pin_config_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_get_pin_configuration_CALL_INSTANCE));
  CMOCK_get_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.get_pin_configuration_CallInstance = CMock_Guts_MemChain(Mock.get_pin_configuration_CallInstance, cmock_guts_index);
  Mock.get_pin_configuration_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_get_pin_configuration(cmock_call_instance, pin_id, pin_config, pin_config_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void get_pin_configuration_CMockReturnMemThruPtr_pin_config(UNITY_LINE_TYPE cmock_line, struct mod_pinctrl_drv_pin_configuration* pin_config, size_t cmock_size)
{
  CMOCK_get_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_pin_configuration_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_pin_config_Used = 1;
  cmock_call_instance->ReturnThruPtr_pin_config_Val = pin_config;
  cmock_call_instance->ReturnThruPtr_pin_config_Size = cmock_size;
}

void get_pin_configuration_CMockIgnoreArg_pin_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_pin_configuration_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pin_id = 1;
}

void get_pin_configuration_CMockIgnoreArg_pin_config(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_get_pin_configuration_CALL_INSTANCE* cmock_call_instance = (CMOCK_get_pin_configuration_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.get_pin_configuration_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pin_config = 1;
}

